@startuml
interface IUniverseSolverFactory
IUniverseSolverFactory : IUniverseSatSolver *createSatSolver()
IUniverseSolverFactory : IUniversePseudoBooleanSolver *createPseudoBooleanSolver()
IUniverseSolverFactory :  IUniverseCspSolver *createCspSolver()
@enduml