stages:
  - build
  - post-build

build-debug:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
    - cmake --build .
  tags:
    - wallon
  except:
    - master

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
    - cmake --build .
  artifacts:
    paths:
      - cmake-build-debug/lib*
  tags:
    - wallon
  only:
    - master

make-doc:
  stage: post-build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
    - cmake --build . --target doc
  artifacts:
    paths:
      - latex/doc.pdf
      - html
  dependencies:
    - build
  tags:
    - wallon
  only:
    - master

