var annotated_dup =
[
    [ "Universe", null, [
      [ "AbstractUniverseIntensionConstraintFactory", "classUniverse_1_1AbstractUniverseIntensionConstraintFactory.html", "classUniverse_1_1AbstractUniverseIntensionConstraintFactory" ],
      [ "IOptimizationSolver", "classUniverse_1_1IOptimizationSolver.html", "classUniverse_1_1IOptimizationSolver" ],
      [ "IUniverseConstraint", "classUniverse_1_1IUniverseConstraint.html", "classUniverse_1_1IUniverseConstraint" ],
      [ "IUniverseCspSolver", "classUniverse_1_1IUniverseCspSolver.html", "classUniverse_1_1IUniverseCspSolver" ],
      [ "IUniverseDomain", "classUniverse_1_1IUniverseDomain.html", "classUniverse_1_1IUniverseDomain" ],
      [ "IUniverseIntensionConstraint", "classUniverse_1_1IUniverseIntensionConstraint.html", "classUniverse_1_1IUniverseIntensionConstraint" ],
      [ "IUniverseIntensionConstraintVisitor", "classUniverse_1_1IUniverseIntensionConstraintVisitor.html", "classUniverse_1_1IUniverseIntensionConstraintVisitor" ],
      [ "IUniverseProblem", "classUniverse_1_1IUniverseProblem.html", "classUniverse_1_1IUniverseProblem" ],
      [ "IUniversePseudoBooleanSolver", "classUniverse_1_1IUniversePseudoBooleanSolver.html", "classUniverse_1_1IUniversePseudoBooleanSolver" ],
      [ "IUniverseSatSolver", "classUniverse_1_1IUniverseSatSolver.html", "classUniverse_1_1IUniverseSatSolver" ],
      [ "IUniverseSolver", "classUniverse_1_1IUniverseSolver.html", "classUniverse_1_1IUniverseSolver" ],
      [ "IUniverseSolverFactory", "classUniverse_1_1IUniverseSolverFactory.html", "classUniverse_1_1IUniverseSolverFactory" ],
      [ "IUniverseVariable", "classUniverse_1_1IUniverseVariable.html", "classUniverse_1_1IUniverseVariable" ],
      [ "JavaBigInteger", "classUniverse_1_1JavaBigInteger.html", "classUniverse_1_1JavaBigInteger" ],
      [ "JavaIterator", "classUniverse_1_1JavaIterator.html", "classUniverse_1_1JavaIterator" ],
      [ "JavaList", "classUniverse_1_1JavaList.html", "classUniverse_1_1JavaList" ],
      [ "JavaMapOfString", "classUniverse_1_1JavaMapOfString.html", "classUniverse_1_1JavaMapOfString" ],
      [ "JavaOptimizationSolver", "classUniverse_1_1JavaOptimizationSolver.html", "classUniverse_1_1JavaOptimizationSolver" ],
      [ "UniverseAssumption", "classUniverse_1_1UniverseAssumption.html", "classUniverse_1_1UniverseAssumption" ],
      [ "UniverseBinaryIntensionConstraint", "classUniverse_1_1UniverseBinaryIntensionConstraint.html", "classUniverse_1_1UniverseBinaryIntensionConstraint" ],
      [ "UniverseConstantIntensionConstraint", "classUniverse_1_1UniverseConstantIntensionConstraint.html", "classUniverse_1_1UniverseConstantIntensionConstraint" ],
      [ "UniverseContradictionException", "classUniverse_1_1UniverseContradictionException.html", "classUniverse_1_1UniverseContradictionException" ],
      [ "UniverseIfThenElseIntensionConstraint", "classUniverse_1_1UniverseIfThenElseIntensionConstraint.html", "classUniverse_1_1UniverseIfThenElseIntensionConstraint" ],
      [ "UniverseIntensionConstraintFactory", "classUniverse_1_1UniverseIntensionConstraintFactory.html", "classUniverse_1_1UniverseIntensionConstraintFactory" ],
      [ "UniverseJavaCspSolver", "classUniverse_1_1UniverseJavaCspSolver.html", "classUniverse_1_1UniverseJavaCspSolver" ],
      [ "UniverseJavaDomain", "classUniverse_1_1UniverseJavaDomain.html", "classUniverse_1_1UniverseJavaDomain" ],
      [ "UniverseJavaIntensionConstraint", "classUniverse_1_1UniverseJavaIntensionConstraint.html", "classUniverse_1_1UniverseJavaIntensionConstraint" ],
      [ "UniverseJavaIntensionConstraintFactory", "classUniverse_1_1UniverseJavaIntensionConstraintFactory.html", "classUniverse_1_1UniverseJavaIntensionConstraintFactory" ],
      [ "UniverseJavaPseudoBooleanSolver", "classUniverse_1_1UniverseJavaPseudoBooleanSolver.html", "classUniverse_1_1UniverseJavaPseudoBooleanSolver" ],
      [ "UniverseJavaSatSolver", "classUniverse_1_1UniverseJavaSatSolver.html", "classUniverse_1_1UniverseJavaSatSolver" ],
      [ "UniverseJavaSolver", "classUniverse_1_1UniverseJavaSolver.html", "classUniverse_1_1UniverseJavaSolver" ],
      [ "UniverseJavaSolverFactory", "classUniverse_1_1UniverseJavaSolverFactory.html", "classUniverse_1_1UniverseJavaSolverFactory" ],
      [ "UniverseJavaVariable", "classUniverse_1_1UniverseJavaVariable.html", "classUniverse_1_1UniverseJavaVariable" ],
      [ "UniverseNaryIntensionConstraint", "classUniverse_1_1UniverseNaryIntensionConstraint.html", "classUniverse_1_1UniverseNaryIntensionConstraint" ],
      [ "UniverseOperatorIntensionConstraint", "classUniverse_1_1UniverseOperatorIntensionConstraint.html", "classUniverse_1_1UniverseOperatorIntensionConstraint" ],
      [ "UniverseUnaryIntensionConstraint", "classUniverse_1_1UniverseUnaryIntensionConstraint.html", "classUniverse_1_1UniverseUnaryIntensionConstraint" ],
      [ "UniverseVariableIntensionConstraint", "classUniverse_1_1UniverseVariableIntensionConstraint.html", "classUniverse_1_1UniverseVariableIntensionConstraint" ]
    ] ]
];