UNIvERSE: Universe::UniverseJavaPseudoBooleanSolver Class Reference
Universe::UniverseJavaPseudoBooleanSolver Class Reference
#include <UniverseJavaPseudoBooleanSolver.hpp>
Public Member Functions
UniverseJavaPseudoBooleanSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaPseudoBooleanSolver () override=default
void addAtLeast (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addAtLeast (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addAtLeast (const std::vector< int > &literals, int degree) override
void addAtMost (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addAtMost (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addAtMost (const std::vector< int > &literals, int degree) override
void addExactly (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addExactly (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addExactly (const std::vector< int > &literals, int degree) override
void addPseudoBoolean (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, bool moreThan, const BigInteger &degree) override
UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
UniverseSolverResult solve (const std::vector< UniverseAssumption< bool >> &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaSatSolver
UniverseJavaSatSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSatSolver () override=default
void addClause (const std::vector< int > &literals) override
Universe::UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
Universe::UniverseSolverResult solve (const std::vector< UniverseAssumption< bool >> &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaSolver
UniverseJavaSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSolver () override=default
const std::map< std::string, Universe::IUniverseVariable * > & getVariablesMapping () override
void interrupt () override
bool isOptimization () override
void loadInstance (const std::string &filename) override
std::map< std::string, Universe::BigInteger > mapSolution () override
int nConstraints () override
int nVariables () override
void reset () override
void setLogFile (const std::string &filename) override
void setTimeout (long seconds) override
void setTimeoutMs (long mseconds) override
void setVerbosity (int level) override
std::vector< BigInteger > solution () override
UniverseSolverResult solve () override
UniverseSolverResult solve (const std::string &filename) override
Universe::IOptimizationSolver * toOptimizationSolver () override
Public Member Functions inherited from Universe::IUniverseSolver
virtual ~IUniverseSolver ()=default
Public Member Functions inherited from Universe::IUniverseSatSolver
~IUniverseSatSolver () override=default
virtual void addAllClauses (const std::vector< std::vector< int >> &clauses)
Public Member Functions inherited from Universe::IUniversePseudoBooleanSolver
~IUniversePseudoBooleanSolver () override=default
Static Protected Member Functions
static Universe::JavaList asList (const std::vector< Universe::BigInteger > &integers, bool hasStar=false)
Static Protected Member Functions inherited from Universe::UniverseJavaSatSolver
static Universe::JavaList asList (const std::vector< int > &integers)
Static Protected Member Functions inherited from Universe::UniverseJavaSolver
template<typename T >
static Universe::JavaList toJavaAssumptions (std::vector< Universe::UniverseAssumption< T >> assumptions, std::function< easyjni::JavaObject(T)> toJavaObject)
static Universe::UniverseSolverResult toUniverseSolverResult (easyjni::JavaObject javaResult)
Additional Inherited Members
Protected Attributes inherited from Universe::UniverseJavaSolver
easyjni::JavaClass * interface
std::map< std::string, Universe::IUniverseVariable * > mapping
easyjni::JavaObject object
Detailed Description
The UniverseJavaPseudoBooleanSolver class defines an adapter for an IUniversePseudoBooleanSolver written in Java (and implementing the JUniverse interface). The solver is run through the Java Native Interface (JNI).
Definition at line 46 of file UniverseJavaPseudoBooleanSolver.hpp.
Constructor & Destructor Documentation
UniverseJavaPseudoBooleanSolver()
UniverseJavaPseudoBooleanSolver::UniverseJavaPseudoBooleanSolver (easyjni::JavaClass * interface, easyjni::JavaObject object)
Creates a UniverseJavaPseudoBooleanSolver.
Parameters
interface The Java interface corresponding to IUniversePseudoBooleanSolver.
object The Java object to adapt.
Definition at line 42 of file UniverseJavaPseudoBooleanSolver.cpp.
~UniverseJavaPseudoBooleanSolver()
Universe::UniverseJavaPseudoBooleanSolver::~UniverseJavaPseudoBooleanSolver () override default
Destroys this UniverseJavaPseudoBooleanSolver.
Member Function Documentation
addAtLeast() [1/3]
void UniverseJavaPseudoBooleanSolver::addAtLeast (const std::vector< int > & literals, const std::vector< int > & coefficients, int degree) override virtual
Adds to this solver an at-least pseudo-Boolean constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be at least equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 81 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAtLeast() [2/3]
void UniverseJavaPseudoBooleanSolver::addAtLeast (const std::vector< int > & literals, const std::vector< Universe::BigInteger > & coefficients, const Universe::BigInteger & degree) override virtual
Adds to this solver an at-least pseudo-Boolean constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be at least equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 90 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addAtLeast() [3/3]
void UniverseJavaPseudoBooleanSolver::addAtLeast (const std::vector< int > & literals, int degree) override virtual
Adds to this solver an at-least cardinality constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The minimum number of literals to satisfy.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 74 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAtMost() [1/3]
void UniverseJavaPseudoBooleanSolver::addAtMost (const std::vector< int > & literals, const std::vector< int > & coefficients, int degree) override virtual
Adds to this solver an at-most pseudo-Boolean constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be at most equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 107 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAtMost() [2/3]
void UniverseJavaPseudoBooleanSolver::addAtMost (const std::vector< int > & literals, const std::vector< Universe::BigInteger > & coefficients, const Universe::BigInteger & degree) override virtual
Adds to this solver an at-most pseudo-Boolean constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be at most equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 116 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addAtMost() [3/3]
void UniverseJavaPseudoBooleanSolver::addAtMost (const std::vector< int > & literals, int degree) override virtual
Adds to this solver an at-most cardinality constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The maximum number of literals to satisfy.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 100 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addExactly() [1/3]
void UniverseJavaPseudoBooleanSolver::addExactly (const std::vector< int > & literals, const std::vector< int > & coefficients, int degree) override virtual
Adds to this solver a pseudo-Boolean constraint defining an equality.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 55 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addExactly() [2/3]
void UniverseJavaPseudoBooleanSolver::addExactly (const std::vector< int > & literals, const std::vector< Universe::BigInteger > & coefficients, const Universe::BigInteger & degree) override virtual
Adds to this solver a pseudo-Boolean constraint defining an equality.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The value to which the weighted sum of literals must be equal.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 64 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addExactly() [3/3]
void UniverseJavaPseudoBooleanSolver::addExactly (const std::vector< int > & literals, int degree) override virtual
Adds to this solver a cardinality constraint defining an equality.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
degree The number of literals to satisfy.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 48 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
addPseudoBoolean()
void UniverseJavaPseudoBooleanSolver::addPseudoBoolean (const std::vector< int > & literals, const std::vector< Universe::BigInteger > & coefficients, bool moreThan, const BigInteger & degree) override virtual
Adds to this solver a pseudo-Boolean constraint.
Parameters
literals The set of literals appearing in the constraint. The vector can be reused since the solver is not supposed to keep a reference to that vector.
coefficients The coefficients of the literals. The vector can be reused since the solver is not supposed to keep a reference to that vector.
moreThan The value true if the constraint is a constraint >= degree, and the value false if it is a constraint <= degree
degree The degree of the pseudo-Boolean constraint.
Exceptions
UniverseContradictionException If the constraint is trivially unsatisfiable.
Implements Universe::IUniversePseudoBooleanSolver.
Definition at line 126 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
asList()
JavaList UniverseJavaPseudoBooleanSolver::asList (const std::vector< Universe::BigInteger > & integers, bool hasStar = false) static protected
Creates a JavaList corresponding to the given vector of BigIntegers.
Parameters
integers The vector of BigIntegers to transform into a list.
Returns
The created list.
Definition at line 146 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::JavaList::from(), and Universe::JavaBigInteger::newInstance().
Referenced by Universe::UniverseJavaCspSolver::addAllDifferent(), Universe::UniverseJavaCspSolver::addAllDifferentMatrix(), Universe::UniverseJavaCspSolver::addAmong(), addAtLeast(), addAtMost(), Universe::UniverseJavaCspSolver::addCardinalityWithConstantValuesAndConstantCounts(), Universe::UniverseJavaCspSolver::addCardinalityWithConstantValuesAndConstantIntervalCounts(), Universe::UniverseJavaCspSolver::addCardinalityWithConstantValuesAndVariableCounts(), Universe::UniverseJavaCspSolver::addCardinalityWithVariableValuesAndConstantCounts(), Universe::UniverseJavaCspSolver::addCardinalityWithVariableValuesAndConstantIntervalCounts(), Universe::UniverseJavaCspSolver::addConflicts(), Universe::UniverseJavaCspSolver::addElementConstantValues(), addExactly(), Universe::UniverseJavaCspSolver::addInstantiation(), Universe::UniverseJavaCspSolver::addNoOverlap(), addPseudoBoolean(), Universe::UniverseJavaCspSolver::addSupport(), Universe::UniverseJavaCspSolver::asList(), Universe::UniverseJavaCspSolver::maximizeExpressionMaximum(), Universe::UniverseJavaCspSolver::maximizeExpressionMinimum(), Universe::UniverseJavaCspSolver::maximizeExpressionNValues(), Universe::UniverseJavaCspSolver::maximizeExpressionProduct(), Universe::UniverseJavaCspSolver::maximizeExpressionSum(), Universe::UniverseJavaCspSolver::maximizeMaximum(), Universe::UniverseJavaCspSolver::maximizeMinimum(), Universe::UniverseJavaCspSolver::maximizeNValues(), Universe::UniverseJavaCspSolver::maximizeProduct(), Universe::UniverseJavaCspSolver::maximizeSum(), Universe::UniverseJavaCspSolver::minimizeExpressionMaximum(), Universe::UniverseJavaCspSolver::minimizeExpressionMinimum(), Universe::UniverseJavaCspSolver::minimizeExpressionNValues(), Universe::UniverseJavaCspSolver::minimizeExpressionProduct(), Universe::UniverseJavaCspSolver::minimizeExpressionSum(), Universe::UniverseJavaCspSolver::minimizeMaximum(), Universe::UniverseJavaCspSolver::minimizeMinimum(), Universe::UniverseJavaCspSolver::minimizeNValues(), Universe::UniverseJavaCspSolver::minimizeProduct(), Universe::UniverseJavaCspSolver::minimizeSum(), and Universe::UniverseJavaCspSolver::newVariable().
solve() [1/2]
UniverseSolverResult UniverseJavaPseudoBooleanSolver::solve (const std::vector< UniverseAssumption< BigInteger >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::UniverseJavaSolver.
Definition at line 141 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSolver::solve().
solve() [2/2]
UniverseSolverResult UniverseJavaPseudoBooleanSolver::solve (const std::vector< UniverseAssumption< bool >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The Boolean assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Implements Universe::IUniverseSatSolver.
Definition at line 136 of file UniverseJavaPseudoBooleanSolver.cpp.
References Universe::UniverseJavaSolver::solve().
The documentation for this class was generated from the following files:
UniverseJavaPseudoBooleanSolver.hpp
UniverseJavaPseudoBooleanSolver.cpp