UNIvERSE: Universe::JavaMapOfString Class Reference
Universe::JavaMapOfString Class Reference
#include <JavaMapOfString.hpp>
Public Member Functions
template<typename V >
std::map< std::string, V > asMap (std::function< V(easyjni::JavaObject)> fct)
void clear ()
easyjni::JavaObject get (const std::string &key)
easyjni::JavaObject operator* ()
void put (const std::string &key, easyjni::JavaObject value)
int size ()
Static Public Member Functions
template<typename V >
static Universe::JavaMapOfString from (const std::map< std::string, V > &map, std::function< easyjni::JavaObject(V)> fct)
static Universe::JavaMapOfString newInstance ()
static Universe::JavaMapOfString of (easyjni::JavaObject jMap)
Detailed Description
The JavaMapOfString class is a wrapper allowing to easily handle Java objects that are instances of Map (and in particular of HashMap), using strings as keys.
Definition at line 49 of file JavaMapOfString.hpp.
Member Function Documentation
asMap()
template<typename V > std::map<std::string, V> Universe::JavaMapOfString::asMap (std::function< V(easyjni::JavaObject)> fct) inline
Gives the representation of this JavaMapOfString as a C++ map.
Template Parameters
V The type of the values in the output map.
Parameters
fct The function to apply to transform each Java object in this map to an instance of V.
Returns
The map representation of this Java object.
Definition at line 174 of file JavaMapOfString.hpp.
References Universe::JavaIterator::forIterable(), and Universe::JavaIterator::hasNext().
clear()
void JavaMapOfString::clear ()
Removes all the elements from this map.
Definition at line 93 of file JavaMapOfString.cpp.
from()
template<typename V > static Universe::JavaMapOfString Universe::JavaMapOfString::from (const std::map< std::string, V > & map, std::function< easyjni::JavaObject(V)> fct) inline static
Creates a new JavaMapOfString from a C++ map.
Template Parameters
V The type of the values in the map.
Parameters
map The map to create a Java map from.
fct The function to apply to transform each value in the map to a JavaObject.
Returns
The created object.
Definition at line 118 of file JavaMapOfString.hpp.
References newInstance(), and put().
Referenced by Universe::UniverseJavaSolver::checkSolution().
get()
JavaObject JavaMapOfString::get (const std::string & key)
Gives the value associated with the given key in this map.
Parameters
key The key of the value to get.
Returns
The value associated with the given key.
Definition at line 86 of file JavaMapOfString.cpp.
newInstance()
JavaMapOfString JavaMapOfString::newInstance () static
Creates a new Java object that is an instance of HashMap.
Returns
The created object.
Definition at line 60 of file JavaMapOfString.cpp.
Referenced by from().
of()
JavaMapOfString JavaMapOfString::of (easyjni::JavaObject jMap) static
Creates a new JavaMapOfString from an existing Java object that is an instance of Map.
Parameters
jMap The existing Java object.
Returns
The wrapper for the object.
Definition at line 65 of file JavaMapOfString.cpp.
Referenced by Universe::UniverseJavaSolver::getVariablesMapping(), and Universe::UniverseJavaSolver::mapSolution().
operator*()
JavaObject JavaMapOfString::operator* ()
Gives the Java object that is wrapped in this JavaMapOfString.
Returns
The wrapped Java object.
Definition at line 70 of file JavaMapOfString.cpp.
put()
void JavaMapOfString::put (const std::string & key, easyjni::JavaObject value)
Puts a key-value pair in this map.
Parameters
key The key to put in this map.
value The value associated with the key.
Definition at line 79 of file JavaMapOfString.cpp.
Referenced by from().
size()
int JavaMapOfString::size ()
Gives the size of this map, measured as its number of key-value pairs.
Returns
The size of this map.
Definition at line 74 of file JavaMapOfString.cpp.
The documentation for this class was generated from the following files:
JavaMapOfString.hpp
JavaMapOfString.cpp