UNIvERSE: Universe::JavaOptimizationSolver Class Reference
Universe::JavaOptimizationSolver Class Reference
#include <JavaOptimizationSolver.hpp>
Public Member Functions
~JavaOptimizationSolver () override=default
Universe::BigInteger getCurrentBound () override
Universe::BigInteger getLowerBound () override
Universe::BigInteger getUpperBound () override
bool isMinimization () override
void setBounds (const Universe::BigInteger &lb, const Universe::BigInteger &ub) override
void setLowerBound (const Universe::BigInteger &lb) override
void setUpperBound (const Universe::BigInteger &ub) override
Public Member Functions inherited from Universe::IOptimizationSolver
virtual ~IOptimizationSolver ()=default
Static Public Member Functions
static IOptimizationSolver * of (easyjni::JavaObject object)
static IOptimizationSolver * of (Universe::UniverseJavaSolver *solver)
Detailed Description
The JavaOptimizationSolver defines an implementation of an IOptimizationSolver in Java (using JNI).
Definition at line 46 of file JavaOptimizationSolver.hpp.
Constructor & Destructor Documentation
~JavaOptimizationSolver()
Universe::JavaOptimizationSolver::~JavaOptimizationSolver () override default
Destroys this IOptimizationSolver.
Member Function Documentation
getCurrentBound()
BigInteger JavaOptimizationSolver::getCurrentBound () override virtual
Gives the current (best) bound that have been found by this solver. It is the current lower or upper bound, depending on whether the problem is a minimization or maximization problem.
Returns
The current bound.
Implements Universe::IOptimizationSolver.
Definition at line 90 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::of().
getLowerBound()
BigInteger JavaOptimizationSolver::getLowerBound () override virtual
Gives the current (best) lower bound of the underlying optimization problem.
Returns
The current lower bound.
Implements Universe::IOptimizationSolver.
Definition at line 70 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::of().
getUpperBound()
BigInteger JavaOptimizationSolver::getUpperBound () override virtual
Gives the current (best) upper bound of the underlying optimization problem.
Returns
The current upper bound.
Implements Universe::IOptimizationSolver.
Definition at line 83 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::of().
isMinimization()
bool JavaOptimizationSolver::isMinimization () override virtual
Checks whether the optimization problem is a minimization problem.
Returns
Whether the underlying problem is a minimization problem.
Implements Universe::IOptimizationSolver.
Definition at line 52 of file JavaOptimizationSolver.cpp.
of() [1/2]
static IOptimizationSolver* Universe::JavaOptimizationSolver::of (easyjni::JavaObject object) static
Creates a JavaOptimizationSolver.
Parameters
object The Java object to adapt.
Returns
The created solver.
Referenced by of(), and Universe::UniverseJavaSolver::toOptimizationSolver().
of() [2/2]
IOptimizationSolver * JavaOptimizationSolver::of (Universe::UniverseJavaSolver * solver) static
Creates a JavaOptimizationSolver.
Parameters
solver The Java solver to adapt.
Returns
The created solver.
Definition at line 48 of file JavaOptimizationSolver.cpp.
References Universe::UniverseJavaSolver::object, and of().
setBounds()
void JavaOptimizationSolver::setBounds (const Universe::BigInteger & lb, const Universe::BigInteger & ub) override virtual
Sets the bounds for the optimization problem to solve.
Parameters
lb The lower bound to set.
ub The upper bound to set.
Implements Universe::IOptimizationSolver.
Definition at line 57 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::newInstance().
setLowerBound()
void JavaOptimizationSolver::setLowerBound (const Universe::BigInteger & lb) override virtual
Sets the lower bound for the optimization problem to solve.
Parameters
lb The lower bound to set.
Implements Universe::IOptimizationSolver.
Definition at line 64 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::newInstance().
setUpperBound()
void JavaOptimizationSolver::setUpperBound (const Universe::BigInteger & ub) override virtual
Sets the upper bound for the optimization problem to solve.
Parameters
ub The upper bound to set.
Implements Universe::IOptimizationSolver.
Definition at line 77 of file JavaOptimizationSolver.cpp.
References Universe::JavaBigInteger::newInstance().
The documentation for this class was generated from the following files:
JavaOptimizationSolver.hpp
JavaOptimizationSolver.cpp