UNIvERSE: Universe::JavaList Class Reference
Universe::JavaList Class Reference
#include <JavaList.hpp>
Public Member Functions
void add (easyjni::JavaObject elt)
template<typename T >
std::vector< T > asVector (std::function< T(easyjni::JavaObject)> fct)
void clear ()
easyjni::JavaObject get (int index)
easyjni::JavaObject operator* ()
int size ()
Static Public Member Functions
template<typename T >
static Universe::JavaList from (const std::vector< T > &vector, std::function< easyjni::JavaObject(T)> fct)
static Universe::JavaList newInstance ()
static Universe::JavaList newInstance (int size)
static Universe::JavaList of (easyjni::JavaObject list)
Detailed Description
The JavaList class is a wrapper allowing to easily handle Java objects that are instances of List (and in particular of ArrayList).
Definition at line 45 of file JavaList.hpp.
Member Function Documentation
add()
void JavaList::add (easyjni::JavaObject elt)
Adds an element to this list.
Parameters
elt The element to add to this list.
Definition at line 81 of file JavaList.cpp.
Referenced by from().
asVector()
template<typename T > std::vector<T> Universe::JavaList::asVector (std::function< T(easyjni::JavaObject)> fct) inline
Gives the representation of this JavaList as a vector.
Template Parameters
T The type of the elements in the output vector.
Parameters
fct The function to apply to transform each Java object in this list to an instance of T.
Returns
The vector representation of this Java object.
Definition at line 174 of file JavaList.hpp.
References get(), and size().
clear()
void JavaList::clear ()
Removes all the elements from this list.
Definition at line 91 of file JavaList.cpp.
from()
template<typename T > static Universe::JavaList Universe::JavaList::from (const std::vector< T > & vector, std::function< easyjni::JavaObject(T)> fct) inline static
Creates a new JavaList from a C++ vector.
Template Parameters
T The type of the elements in the vector.
Parameters
vector The vector to create a list from.
fct The function to apply to transform each element in the vector to a JavaObject.
Returns
The created object.
Definition at line 119 of file JavaList.hpp.
References add(), newInstance(), and size().
Referenced by Universe::UniverseJavaSatSolver::asList(), Universe::UniverseJavaCspSolver::asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), Universe::UniverseJavaSolver::decisionVariables(), Universe::UniverseJavaSolver::toJavaAssumptions(), and Universe::UniverseJavaSolver::valueHeuristicStatic().
get()
JavaObject JavaList::get (int index)
Gives the element in this list at the specified index.
Parameters
index The index of the element.
Returns
The element at the given index.
Definition at line 86 of file JavaList.cpp.
Referenced by asVector().
newInstance() [1/2]
JavaList JavaList::newInstance () static
Creates a new Java object that is an instance of ArrayList.
Returns
The created object.
Definition at line 56 of file JavaList.cpp.
Referenced by from().
newInstance() [2/2]
JavaList JavaList::newInstance (int size) static
Creates a new Java object that is an instance of ArrayList, with the given initial size.
Parameters
size The initial size of the list to create.
Returns
The created object.
Definition at line 61 of file JavaList.cpp.
References size().
of()
JavaList JavaList::of (easyjni::JavaObject list) static
Creates a new JavaList from an existing Java object that is an instance of List.
Parameters
list The existing Java object.
Returns
The wrapper for the object.
Definition at line 67 of file JavaList.cpp.
Referenced by Universe::UniverseJavaSolver::getAuxiliaryVariables(), and Universe::UniverseJavaSolver::solution().
operator*()
JavaObject JavaList::operator* ()
Gives the Java object that is wrapped in this JavaList.
Returns
The wrapped Java object.
Definition at line 72 of file JavaList.cpp.
size()
int JavaList::size ()
Gives the size of this list, measured as its number of elements.
Returns
The size of this list.
Definition at line 76 of file JavaList.cpp.
Referenced by asVector(), from(), and newInstance().
The documentation for this class was generated from the following files:
JavaList.hpp
JavaList.cpp