UNIvERSE: Universe::UniverseJavaSatSolver Class Reference
Universe::UniverseJavaSatSolver Class Reference
#include <UniverseJavaSatSolver.hpp>
Public Member Functions
UniverseJavaSatSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSatSolver () override=default
void addClause (const std::vector< int > &literals) override
Universe::UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
Universe::UniverseSolverResult solveBoolean (const std::vector< UniverseAssumption< bool >> &assumptions) override
UniverseSolverResult solveDimacs (const std::vector< int > &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaSolver
UniverseJavaSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSolver () override=default
void addSearchListener (Universe::IUniverseSearchListener *listener) override
bool checkSolution () override
bool checkSolution (const std::map< std::string, Universe::BigInteger > &assignment) override
void decisionVariables (const std::vector< std::string > &variables) override
const std::vector< std::string > & getAuxiliaryVariables () override
const vector< IUniverseConstraint * > & getConstraints () override
const std::map< std::string, Universe::IUniverseVariable * > & getVariablesMapping () override
void interrupt () override
bool isOptimization () override
void loadInstance (const std::string &filename) override
std::map< std::string, Universe::BigInteger > mapSolution () override
std::map< std::string, Universe::BigInteger > mapSolution (bool excludeAux) override
int nConstraints () override
int nVariables () override
void removeSearchListener (Universe::IUniverseSearchListener *listener) override
void reset () override
void setLogFile (const std::string &filename) override
void setLogStream (std::ostream &stream) override
void setTimeout (long seconds) override
void setTimeoutMs (long mseconds) override
void setVerbosity (int level) override
std::vector< Universe::BigInteger > solution () override
UniverseSolverResult solve () override
UniverseSolverResult solve (const std::string &filename) override
Universe::IOptimizationSolver * toOptimizationSolver () override
void valueHeuristicStatic (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &orderedValues) override
Public Member Functions inherited from Universe::IUniverseSolver
virtual ~IUniverseSolver ()=default
Public Member Functions inherited from Universe::IUniverseSatSolver
~IUniverseSatSolver () override=default
virtual void addAllClauses (const std::vector< std::vector< int >> &clauses)
Static Protected Member Functions
static Universe::JavaList asList (const std::vector< int > &integers)
Static Protected Member Functions inherited from Universe::UniverseJavaSolver
template<typename T >
static Universe::JavaList toJavaAssumptions (std::vector< Universe::UniverseAssumption< T >> assumptions, std::function< easyjni::JavaObject(T)> toJavaObject)
static Universe::UniverseSolverResult toUniverseSolverResult (easyjni::JavaObject javaResult)
Additional Inherited Members
Protected Attributes inherited from Universe::UniverseJavaSolver
std::vector< std::string > auxiliaryVariables
std::vector< IUniverseConstraint * > constraints
easyjni::JavaClass * interface
std::map< std::string, Universe::IUniverseVariable * > mapping
easyjni::JavaObject object
Detailed Description
The UniverseJavaSatSolver class defines an adapter for an IUniverseSatSolver written in Java (and implementing the JUniverse interface). The solver is run through the Java Native Interface (JNI).
Definition at line 45 of file UniverseJavaSatSolver.hpp.
Constructor & Destructor Documentation
UniverseJavaSatSolver()
UniverseJavaSatSolver::UniverseJavaSatSolver (easyjni::JavaClass * interface, easyjni::JavaObject object)
Creates a UniverseJavaSatSolver.
Parameters
interface The Java interface corresponding to IUniverseSatSolver.
object The Java object to adapt.
Definition at line 41 of file UniverseJavaSatSolver.cpp.
~UniverseJavaSatSolver()
Universe::UniverseJavaSatSolver::~UniverseJavaSatSolver () override default
Destroys this UniverseJavaSatSolver.
Member Function Documentation
addClause()
void UniverseJavaSatSolver::addClause (const std::vector< int > & literals) override virtual
Adds to this solver a clause from a set of literals. The literals are represented by non-zero integers such that opposite literals are represented by opposite values (following the classical DIMACS way of representing literals).
Parameters
literals The literals of the clause to add.
Exceptions
UniverseContradictionException If the clause to add is inconsistent.
Implements Universe::IUniverseSatSolver.
Definition at line 46 of file UniverseJavaSatSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
asList()
JavaList UniverseJavaSatSolver::asList (const std::vector< int > & integers) static protected
Creates a JavaList corresponding to the given vector of integers.
Parameters
integers The vector of integers to transform into a list.
Returns
The created list.
Definition at line 78 of file UniverseJavaSatSolver.cpp.
References Universe::JavaList::from().
Referenced by Universe::UniverseJavaPseudoBooleanSolver::addAtLeast(), Universe::UniverseJavaPseudoBooleanSolver::addAtMost(), addClause(), Universe::UniverseJavaPseudoBooleanSolver::addExactly(), Universe::UniverseJavaCspSolver::addInstantiation(), Universe::UniverseJavaPseudoBooleanSolver::addPseudoBoolean(), Universe::UniverseJavaCspSolver::newVariable(), and solveDimacs().
solve()
UniverseSolverResult UniverseJavaSatSolver::solve (const std::vector< UniverseAssumption< BigInteger >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::UniverseJavaSolver.
Definition at line 74 of file UniverseJavaSatSolver.cpp.
References Universe::UniverseJavaSolver::solve().
solveBoolean()
UniverseSolverResult UniverseJavaSatSolver::solveBoolean (const std::vector< UniverseAssumption< bool >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::IUniverseSatSolver.
Definition at line 60 of file UniverseJavaSatSolver.cpp.
References Universe::UniverseJavaSolver::interface, Universe::UniverseJavaSolver::toJavaAssumptions(), and Universe::UniverseJavaSolver::toUniverseSolverResult().
Referenced by Universe::UniverseJavaPseudoBooleanSolver::solveBoolean().
solveDimacs()
UniverseSolverResult UniverseJavaSatSolver::solveDimacs (const std::vector< int > & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving (as a set of literals).
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::IUniverseSatSolver.
Definition at line 52 of file UniverseJavaSatSolver.cpp.
References asList(), Universe::UniverseJavaSolver::interface, and Universe::UniverseJavaSolver::toUniverseSolverResult().
Referenced by Universe::UniverseJavaPseudoBooleanSolver::solveDimacs().
The documentation for this class was generated from the following files:
UniverseJavaSatSolver.hpp
UniverseJavaSatSolver.cpp