UNIvERSE: Universe::IUniverseIntensionConstraint Class Reference
Universe::IUniverseIntensionConstraint Class Reference abstract
#include <IUniverseIntensionConstraint.hpp>
Public Member Functions
virtual ~IUniverseIntensionConstraint ()=default
virtual void accept (IUniverseIntensionConstraintVisitor *visitor)=0
Detailed Description
The IUniverseIntensionConstraint defines an interface for representing the abstract syntax tree of an intension constraint.
Definition at line 42 of file IUniverseIntensionConstraint.hpp.
Constructor & Destructor Documentation
~IUniverseIntensionConstraint()
virtual Universe::IUniverseIntensionConstraint::~IUniverseIntensionConstraint () virtual default
Destroys this IUniverseIntensionConstraint.
Member Function Documentation
accept()
virtual void Universe::IUniverseIntensionConstraint::accept (IUniverseIntensionConstraintVisitor * visitor) pure virtual
Accepts an IUniverseIntensionConstraintVisitor.
Parameters
visitor The visitor to accept.
Implemented in Universe::UniverseVariableIntensionConstraint, Universe::UniverseUnaryIntensionConstraint, Universe::UniverseSetIntensionConstraint, Universe::UniverseRangeIntensionConstraint, Universe::UniverseNaryIntensionConstraint, Universe::UniverseJavaIntensionConstraint, Universe::UniverseIfThenElseIntensionConstraint, Universe::UniverseConstantIntensionConstraint, and Universe::UniverseBinaryIntensionConstraint.
Referenced by Universe::UniverseBinaryIntensionConstraint::accept(), Universe::UniverseIfThenElseIntensionConstraint::accept(), and Universe::UniverseUnaryIntensionConstraint::accept().
The documentation for this class was generated from the following file:
IUniverseIntensionConstraint.hpp