UNIvERSE: Universe::UniverseJavaDomain Class Reference
Universe::UniverseJavaDomain Class Reference
#include <UniverseJavaDomain.hpp>
Public Member Functions
~UniverseJavaDomain () override=default
size_t currentSize () const override
const std::vector< Universe::BigInteger > & getCurrentValues () override
const std::vector< Universe::BigInteger > & getValues () override
Universe::BigInteger max () const override
Universe::BigInteger min () const override
easyjni::JavaObject operator* ()
size_t size () const override
Public Member Functions inherited from Universe::IUniverseDomain
virtual ~IUniverseDomain ()=default
Static Public Member Functions
static Universe::IUniverseDomain * of (easyjni::JavaObject domain)
Detailed Description
The UniverseJavaDomain class defines an adapter for an IUniverseDomain written in Java (and implementing the interface provided by JUniverse).
Definition at line 45 of file UniverseJavaDomain.hpp.
Constructor & Destructor Documentation
~UniverseJavaDomain()
Universe::UniverseJavaDomain::~UniverseJavaDomain () override default
Destroys this UniverseJavaDomain.
Member Function Documentation
currentSize()
size_t UniverseJavaDomain::currentSize () const override virtual
Gives the current size of this domain, measured in number of values.
Returns
The current size of this domain.
Implements Universe::IUniverseDomain.
Definition at line 117 of file UniverseJavaDomain.cpp.
getCurrentValues()
const vector< Universe::BigInteger > & UniverseJavaDomain::getCurrentValues () override virtual
Gives the list of current values of this domain.
Returns
The list of current values.
Implements Universe::IUniverseDomain.
Definition at line 100 of file UniverseJavaDomain.cpp.
References Universe::JavaIterator::forIterable(), Universe::JavaIterator::hasNext(), and Universe::JavaBigInteger::of().
getValues()
const vector< Universe::BigInteger > & UniverseJavaDomain::getValues () override virtual
Gives the list of initial values of this domain.
Returns
The list of initial values.
Implements Universe::IUniverseDomain.
Definition at line 83 of file UniverseJavaDomain.cpp.
References Universe::JavaIterator::forIterable(), Universe::JavaIterator::hasNext(), and Universe::JavaBigInteger::of().
max()
BigInteger UniverseJavaDomain::max () const override virtual
Gives the maximum value of this domain.
Returns
The maximum value.
Implements Universe::IUniverseDomain.
Definition at line 77 of file UniverseJavaDomain.cpp.
References Universe::JavaBigInteger::asBigInteger(), and Universe::JavaBigInteger::of().
min()
BigInteger UniverseJavaDomain::min () const override virtual
Gives the minimum value of this domain.
Returns
The minimum value.
Implements Universe::IUniverseDomain.
Definition at line 71 of file UniverseJavaDomain.cpp.
References Universe::JavaBigInteger::asBigInteger(), and Universe::JavaBigInteger::of().
of()
IUniverseDomain * UniverseJavaDomain::of (easyjni::JavaObject domain) static
Creates a new UniverseJavaDomain from an existing Java object that is an instance of IUniverseDomain.
Parameters
domain The existing Java object.
Returns
The wrapper for the object.
Definition at line 57 of file UniverseJavaDomain.cpp.
Referenced by Universe::UniverseJavaVariable::getDomain().
operator*()
JavaObject UniverseJavaDomain::operator* ()
Gives the Java object that is wrapped in this UniverseJavaDomain.
Returns
The wrapped Java object.
Definition at line 62 of file UniverseJavaDomain.cpp.
size()
size_t UniverseJavaDomain::size () const override virtual
Gives the size of this domain, measured in number of values.
Returns
The size of this domain.
Implements Universe::IUniverseDomain.
Definition at line 66 of file UniverseJavaDomain.cpp.
The documentation for this class was generated from the following files:
UniverseJavaDomain.hpp
UniverseJavaDomain.cpp