UNIvERSE: Universe::UniverseJavaVariable Class Reference
Universe::UniverseJavaVariable Class Reference
#include <UniverseJavaVariable.hpp>
Public Member Functions
~UniverseJavaVariable () override=default
Universe::IUniverseDomain * getDomain () const override
int getId () const override
const std::string & getName () const override
easyjni::JavaObject operator* ()
Public Member Functions inherited from Universe::IUniverseVariable
virtual ~IUniverseVariable ()=default
Static Public Member Functions
static Universe::IUniverseVariable * of (easyjni::JavaObject variable)
Detailed Description
The UniverseJavaVariable class defines an adapter for an IUniverseVariable written in Java (and implementing the interface provided by JUniverse).
Definition at line 45 of file UniverseJavaVariable.hpp.
Constructor & Destructor Documentation
~UniverseJavaVariable()
Universe::UniverseJavaVariable::~UniverseJavaVariable () override default
Destroys this UniverseJavaVariable.
Member Function Documentation
getDomain()
IUniverseDomain * UniverseJavaVariable::getDomain () const override virtual
Gives the domain of this variable.
Returns
The domain of this variable.
Implements Universe::IUniverseVariable.
Definition at line 78 of file UniverseJavaVariable.cpp.
References Universe::UniverseJavaDomain::of().
getId()
int UniverseJavaVariable::getId () const override virtual
Gives the internal identifier of this variable.
Returns
The internal identifier of this variable.
Implements Universe::IUniverseVariable.
Definition at line 73 of file UniverseJavaVariable.cpp.
getName()
const string & UniverseJavaVariable::getName () const override virtual
Gives the name of this variable.
Returns
The name of this variable.
Implements Universe::IUniverseVariable.
Definition at line 69 of file UniverseJavaVariable.cpp.
of()
IUniverseVariable * UniverseJavaVariable::of (easyjni::JavaObject variable) static
Creates a new UniverseJavaVariable from an existing Java object that is an instance of IUniverseVariable.
Parameters
variable The existing Java object.
Returns
The wrapper for the object.
Definition at line 60 of file UniverseJavaVariable.cpp.
Referenced by Universe::UniverseJavaProblem::getVariables(), Universe::UniverseJavaSolver::getVariablesMapping(), and Universe::UniverseJavaConstraint::scope().
operator*()
JavaObject UniverseJavaVariable::operator* ()
Gives the Java object that is wrapped in this UniverseJavaVariable.
Returns
The wrapped Java object.
Definition at line 65 of file UniverseJavaVariable.cpp.
The documentation for this class was generated from the following files:
UniverseJavaVariable.hpp
UniverseJavaVariable.cpp