UNIvERSE: Universe::UniverseJavaProblem Class Reference
Universe::UniverseJavaProblem Class Reference
#include <UniverseJavaProblem.hpp>
Public Member Functions
~UniverseJavaProblem () override=default
void addConstraint (Universe::IUniverseConstraint *constraint) override
void addVariable (Universe::IUniverseVariable *variable) override
const std::vector< Universe::IUniverseConstraint * > & getConstraints () override
const std::vector< Universe::IUniverseVariable * > & getVariables () override
easyjni::JavaObject operator* ()
Public Member Functions inherited from Universe::IUniverseProblem
virtual ~IUniverseProblem ()=default
Static Public Member Functions
static Universe::IUniverseProblem * of (easyjni::JavaObject problem)
Detailed Description
The UniverseJavaProblem class defines an adapter for an IUniverseProblem written in Java (and implementing the interface provided by JUniverse).
Definition at line 44 of file UniverseJavaProblem.hpp.
Constructor & Destructor Documentation
~UniverseJavaProblem()
Universe::UniverseJavaProblem::~UniverseJavaProblem () override default
Destroys this UniverseJavaProblem.
Member Function Documentation
addConstraint()
void UniverseJavaProblem::addConstraint (Universe::IUniverseConstraint * constraint) override virtual
Adds a constraint to this problem.
Parameters
constraint The constraint to add.
Implements Universe::IUniverseProblem.
Definition at line 90 of file UniverseJavaProblem.cpp.
addVariable()
void UniverseJavaProblem::addVariable (Universe::IUniverseVariable * variable) override virtual
Adds a variable to this problem.
Parameters
variable The variable to add.
Implements Universe::IUniverseProblem.
Definition at line 69 of file UniverseJavaProblem.cpp.
getConstraints()
const vector< IUniverseConstraint * > & UniverseJavaProblem::getConstraints () override virtual
Gives the constraints in this problem.
Returns
The constraints in this problem.
Implements Universe::IUniverseProblem.
Definition at line 94 of file UniverseJavaProblem.cpp.
References Universe::JavaIterator::forIterable(), Universe::JavaIterator::hasNext(), and Universe::UniverseJavaConstraint::of().
getVariables()
const vector< IUniverseVariable * > & UniverseJavaProblem::getVariables () override virtual
Gives the variables in this problem.
Returns
The variables in this problem.
Implements Universe::IUniverseProblem.
Definition at line 73 of file UniverseJavaProblem.cpp.
References Universe::JavaIterator::forIterable(), Universe::JavaIterator::hasNext(), and Universe::UniverseJavaVariable::of().
of()
IUniverseProblem * UniverseJavaProblem::of (easyjni::JavaObject problem) static
Creates a new UniverseJavaProblem from an existing Java object that is an instance of IUniverseProblem.
Parameters
problem The existing Java object.
Returns
The wrapper for the object.
Definition at line 60 of file UniverseJavaProblem.cpp.
operator*()
JavaObject UniverseJavaProblem::operator* ()
Gives the Java object that is wrapped in this UniverseJavaProblem.
Returns
The wrapped Java object.
Definition at line 65 of file UniverseJavaProblem.cpp.
The documentation for this class was generated from the following files:
UniverseJavaProblem.hpp
UniverseJavaProblem.cpp