UNIvERSE: Universe::JavaBigInteger Class Reference
Universe::JavaBigInteger Class Reference
#include <JavaBigInteger.hpp>
Public Member Functions
Universe::BigInteger asBigInteger ()
easyjni::JavaObject operator* ()
Static Public Member Functions
static Universe::JavaBigInteger newInstance (const Universe::BigInteger &value)
static Universe::JavaBigInteger newInstance (int value)
static Universe::JavaBigInteger of (easyjni::JavaObject bigInteger)
Detailed Description
The JavaBigInteger class is a wrapper allowing to easily handle Java objects that are instances of BigInteger.
Definition at line 44 of file JavaBigInteger.hpp.
Member Function Documentation
asBigInteger()
BigInteger JavaBigInteger::asBigInteger ()
Gives the representation of this JavaBigInteger as a native BigInteger.
Returns
The BigInteger representation of this Java object.
Definition at line 76 of file JavaBigInteger.cpp.
References Universe::bigIntegerValueOf().
Referenced by Universe::UniverseJavaSolver::mapSolution(), Universe::UniverseJavaDomain::max(), Universe::UniverseJavaDomain::min(), and Universe::UniverseJavaSolver::solution().
newInstance() [1/2]
JavaBigInteger JavaBigInteger::newInstance (const Universe::BigInteger & value) static
Creates a new Java object that is an instance of BigInteger with the given value.
Parameters
value The value of the BigInteger to create.
Returns
The created object.
Definition at line 60 of file JavaBigInteger.cpp.
References Universe::toString().
newInstance() [2/2]
JavaBigInteger JavaBigInteger::newInstance (int value) static
Creates a new Java object that is an instance of BigInteger with the given value.
Parameters
value The value of the BigInteger to create.
Returns
The created object.
Definition at line 53 of file JavaBigInteger.cpp.
Referenced by Universe::UniverseJavaCspSolver::addAmong(), Universe::UniverseJavaPseudoBooleanSolver::addAtLeast(), Universe::UniverseJavaCspSolver::addAtLeast(), Universe::UniverseJavaPseudoBooleanSolver::addAtMost(), Universe::UniverseJavaCspSolver::addAtMost(), Universe::UniverseJavaPseudoBooleanSolver::addExactly(), Universe::UniverseJavaCspSolver::addExactly(), Universe::UniverseJavaCspSolver::addInstantiation(), Universe::UniverseJavaPseudoBooleanSolver::addPseudoBoolean(), Universe::UniverseJavaPseudoBooleanSolver::asList(), Universe::UniverseJavaCspSolver::newVariable(), Universe::JavaOptimizationSolver::setBounds(), Universe::JavaOptimizationSolver::setLowerBound(), Universe::JavaOptimizationSolver::setUpperBound(), and Universe::UniverseJavaSolver::solve().
of()
JavaBigInteger JavaBigInteger::of (easyjni::JavaObject bigInteger) static
Creates a new JavaBigInteger from an existing Java object that is an instance of BigInteger.
Parameters
bigInteger The existing Java object.
Returns
The wrapper for the object.
Definition at line 67 of file JavaBigInteger.cpp.
Referenced by Universe::JavaOptimizationSolver::getCurrentBound(), Universe::JavaOptimizationSolver::getLowerBound(), Universe::JavaOptimizationSolver::getUpperBound(), Universe::UniverseJavaDomain::getValues(), Universe::UniverseJavaSolver::mapSolution(), Universe::UniverseJavaDomain::max(), Universe::UniverseJavaDomain::min(), and Universe::UniverseJavaSolver::solution().
operator*()
JavaObject JavaBigInteger::operator* ()
Gives the Java object that is wrapped in this JavaBigInteger.
Returns
The wrapped Java object.
Definition at line 72 of file JavaBigInteger.cpp.
The documentation for this class was generated from the following files:
JavaBigInteger.hpp
JavaBigInteger.cpp