UNIvERSE: Universe::JavaIterator Class Reference
Universe::JavaIterator Class Reference
#include <JavaIterator.hpp>
Public Member Functions
bool hasNext ()
easyjni::JavaObject next ()
easyjni::JavaObject operator* ()
void remove ()
Static Public Member Functions
static Universe::JavaIterator forIterable (const easyjni::JavaObject &iterable)
static Universe::JavaIterator of (easyjni::JavaObject iterator)
Detailed Description
The JavaIterator class is a wrapper allowing to easily handle Java objects that are instances of Iterator.
Definition at line 45 of file JavaIterator.hpp.
Member Function Documentation
forIterable()
JavaIterator JavaIterator::forIterable (const easyjni::JavaObject & iterable) static
Creates a new JavaIterator from an existing Java object that is an instance of Iterable.
Parameters
iterable The existing Java iterable object.
Returns
The wrapper for the iterator of the object.
Definition at line 56 of file JavaIterator.cpp.
Referenced by Universe::JavaMapOfString::asMap(), and Universe::UniverseJavaDomain::getValues().
hasNext()
bool JavaIterator::hasNext ()
Checks whether there is a next element to iterate over.
Returns
If there is a next element.
Definition at line 72 of file JavaIterator.cpp.
Referenced by Universe::JavaMapOfString::asMap(), and Universe::UniverseJavaDomain::getValues().
next()
JavaObject JavaIterator::next ()
Gives the next element of the iteration.
Returns
The next element.
Definition at line 77 of file JavaIterator.cpp.
of()
JavaIterator JavaIterator::of (easyjni::JavaObject iterator) static
Creates a new JavaIterator from an existing Java object that is an instance of Iterator.
Parameters
iterator The existing Java object.
Returns
The wrapper for the object.
Definition at line 63 of file JavaIterator.cpp.
operator*()
JavaObject JavaIterator::operator* ()
Gives the Java object that is wrapped in this JavaIterator.
Returns
The wrapped Java object.
Definition at line 68 of file JavaIterator.cpp.
remove()
void JavaIterator::remove ()
Removes the current element.
Definition at line 82 of file JavaIterator.cpp.
The documentation for this class was generated from the following files:
JavaIterator.hpp
JavaIterator.cpp