UNIvERSE: Universe::UniverseJavaCspSolver Class Reference
Universe::UniverseJavaCspSolver Class Reference
#include <UniverseJavaCspSolver.hpp>
Public Member Functions
UniverseJavaCspSolver (easyjni::JavaClass *interface, const easyjni::JavaObject &object)
~UniverseJavaCspSolver () override=default
void addAllDifferent (const std::vector< std::string > &variables) override
void addAllDifferent (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &except) override
void addAllDifferentIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints) override
void addAllDifferentList (const std::vector< std::vector< std::string >> &variableLists) override
void addAllDifferentList (const std::vector< std::vector< std::string >> &variableLists, const std::vector< std::vector< Universe::BigInteger >> &except) override
void addAllDifferentMatrix (const std::vector< std::vector< std::string >> &variableMatrix) override
void addAllDifferentMatrix (const std::vector< std::vector< std::string >> &variableMatrix, const std::vector< Universe::BigInteger > &except) override
void addAllEqual (const std::vector< std::string > &variables) override
void addAllEqualIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void addAmong (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::string &count) override
void addAmong (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const Universe::BigInteger &count) override
void addAtLeast (const std::vector< std::string > &variables, const Universe::BigInteger &value, const Universe::BigInteger &count) override
void addAtMost (const std::vector< std::string > &variables, const Universe::BigInteger &value, const Universe::BigInteger &count) override
void addBiDimensionalNoOverlap (const std::vector< std::string > &xVariables, const std::vector< std::string > &yVariables, const std::vector< std::string > &xLength, const std::vector< Universe::BigInteger > &yLength) override
void addBiDimensionalNoOverlap (const std::vector< std::string > &xVariables, const std::vector< std::string > &yVariables, const std::vector< std::string > &xLength, const std::vector< Universe::BigInteger > &yLength, bool zeroIgnored) override
void addBinPacking (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, Universe::UniverseRelationalOperator op, const std::string &variable) override
void addBinPacking (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addBinPacking (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addBinPacking (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addBinPackingWithConstantCapacities (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, const std::vector< Universe::BigInteger > &capacities, bool loads) override
void addBinPackingWithVariableCapacities (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &sizes, const std::vector< std::string > &capacities, bool loads) override
void addCardinalityWithConstantValuesAndConstantCounts (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::vector< Universe::BigInteger > &occurs, bool closed) override
void addCardinalityWithConstantValuesAndConstantIntervalCounts (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::vector< Universe::BigInteger > &occursMin, const std::vector< Universe::BigInteger > &occursMax, bool closed) override
void addCardinalityWithConstantValuesAndVariableCounts (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::vector< std::string > &occurs, bool closed) override
void addCardinalityWithVariableValuesAndConstantCounts (const std::vector< std::string > &variables, const std::vector< std::string > &values, const std::vector< Universe::BigInteger > &occurs, bool closed) override
void addCardinalityWithVariableValuesAndConstantIntervalCounts (const std::vector< std::string > &variables, const std::vector< std::string > &values, const std::vector< Universe::BigInteger > &occursMin, const std::vector< Universe::BigInteger > &occursMax, bool closed) override
void addCardinalityWithVariableValuesAndVariableCounts (const std::vector< std::string > &variables, const std::vector< std::string > &values, const std::vector< std::string > &occurs, bool closed) override
void addChannel (const std::vector< std::string > &variables, int startIndex) override
void addChannel (const std::vector< std::string > &variables, int startIndex, const std::string &value) override
void addChannel (const std::vector< std::string > &variables, int startIndex, const std::vector< std::string > &otherVariables, int otherStartIndex) override
void addCircuit (const std::vector< std::string > &variables, int startIndex) override
void addCircuit (const std::vector< std::string > &variables, int startIndex, const std::string &size) override
void addCircuit (const std::vector< std::string > &variables, int startIndex, const Universe::BigInteger &size) override
void addClause (const std::vector< std::string > &positive, const std::vector< std::string > &negative) override
void addConflicts (const std::string &variable, const std::vector< Universe::BigInteger > &forbiddenValues, bool hasStar) override
void addConflicts (const std::vector< std::string > &variableTuple, const std::vector< std::vector< Universe::BigInteger >> &forbiddenValues, bool hasStar) override
void addConflictsSymbolic (const std::string &variable, const std::vector< std::string > &forbiddenValues, bool hasStar) override
void addConflictsSymbolic (const std::vector< std::string > &variableTuple, const std::vector< std::vector< std::string >> &forbiddenValues, bool hasStar) override
void addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &values, Universe::UniverseRelationalOperator op, const std::string &count) override
void addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &values, Universe::UniverseRelationalOperator op, const Universe::BigInteger &count) override
void addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCountWithConstantValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, Universe::UniverseRelationalOperator op, const std::string &count) override
void addCountWithConstantValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, Universe::UniverseRelationalOperator op, const Universe::BigInteger &count) override
void addCountWithConstantValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCountWithConstantValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCountWithVariableValues (const std::vector< std::string > &variables, const std::vector< std::string > &values, Universe::UniverseRelationalOperator op, const std::string &count) override
void addCountWithVariableValues (const std::vector< std::string > &variables, const std::vector< std::string > &values, Universe::UniverseRelationalOperator op, const Universe::BigInteger &count) override
void addCountWithVariableValues (const std::vector< std::string > &variables, const std::vector< std::string > &values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCountWithVariableValues (const std::vector< std::string > &variables, const std::vector< std::string > &values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< Universe::BigInteger > &lengths, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< Universe::BigInteger > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &ends, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const std::string &value) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > &origins, const std::vector< std::string > &lengths, const std::vector< std::string > &heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addElement (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const std::string &variable) override
void addElement (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addElement (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addElement (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addElement (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &value) override
void addElement (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addElement (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addElement (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseRelationalOperator op, const std::string &value) override
void addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addElementConstantValues (const std::vector< Universe::BigInteger > &values, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const std::string &variable) override
void addElementConstantValues (const std::vector< Universe::BigInteger > &values, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addElementConstantValues (const std::vector< Universe::BigInteger > &values, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addElementConstantValues (const std::vector< Universe::BigInteger > &values, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addElementMatrix (const std::vector< std::vector< std::string >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseRelationalOperator op, const std::string &value) override
void addElementMatrix (const std::vector< std::vector< std::string >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addElementMatrix (const std::vector< std::vector< std::string >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addElementMatrix (const std::vector< std::vector< std::string >> &matrix, int startRowIndex, const std::string &rowIndex, int startColIndex, const std::string &colIndex, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addExactly (const std::vector< std::string > &variables, const Universe::BigInteger &value, const std::string &count) override
void addExactly (const std::vector< std::string > &variables, const Universe::BigInteger &value, const Universe::BigInteger &count) override
void addFlow (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &balance, const std::vector< std::vector< Universe::BigInteger >> &edges) override
void addFlow (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &balance, const std::vector< std::vector< Universe::BigInteger >> &edges, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator op, const std::string &totalCost) override
void addFlow (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &balance, const std::vector< std::vector< Universe::BigInteger >> &edges, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator op, const Universe::BigInteger &totalCost) override
void addFlow (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &balance, const std::vector< std::vector< Universe::BigInteger >> &edges, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addFlow (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &balance, const std::vector< std::vector< Universe::BigInteger >> &edges, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addInstantiation (const std::string &variable, const std::string &value) override
void addInstantiation (const std::string &variable, const Universe::BigInteger &value) override
void addInstantiation (const std::string &variable, int value) override
void addInstantiation (const std::vector< std::string > &variables, const std::vector< int > &values) override
void addInstantiation (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values) override
void addInstantiationSymbolic (const std::vector< std::string > &variables, const std::vector< std::string > &values) override
void addIntension (Universe::IUniverseIntensionConstraint *constr) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const std::string &wVariable, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const std::string &pVariable) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const std::string &wVariable, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger &pValue) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const std::string &wVariable, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > &pSet) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const std::string &wVariable, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger &pMin, const Universe::BigInteger &pMax) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger &wValue, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const std::string &pVariable) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger &wValue, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger &pValue) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger &wValue, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > &pSet) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger &wValue, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger &pMin, const Universe::BigInteger &pMax) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > &wSet, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const std::string &pVariable) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > &wSet, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger &pValue) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > &wSet, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > &pSet) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > &wSet, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger &pMin, const Universe::BigInteger &pMax) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger &wMin, const Universe::BigInteger &wMax, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const std::string &pVariable) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger &wMin, const Universe::BigInteger &wMax, const std::vector< Universe::BigInteger > &profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger &pValue) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger &wMin, const Universe::BigInteger &wMax, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > &pSet) override
void addKnapsack (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger &wMin, const Universe::BigInteger &wMax, const std::vector< Universe::BigInteger > &profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger &pMin, const Universe::BigInteger &pMax) override
void addLex (const std::vector< std::vector< std::string >> &tuples, Universe::UniverseRelationalOperator op) override
void addLex (const std::vector< std::vector< std::string >> &variables, const std::vector< std::vector< Universe::BigInteger >> &limit, Universe::UniverseRelationalOperator op) override
void addLexMatrix (const std::vector< std::vector< std::string >> &matrix, Universe::UniverseRelationalOperator op) override
void addLogical (const std::string &variable, bool equiv, Universe::UniverseBooleanOperator op, const std::vector< std::string > &variables) override
void addLogical (const std::string &variable, const std::string &left, Universe::UniverseRelationalOperator op, const std::string &right) override
void addLogical (const std::string &variable, const std::string &left, Universe::UniverseRelationalOperator op, const Universe::BigInteger &right) override
void addLogical (Universe::UniverseBooleanOperator op, const std::vector< std::string > &variables) override
void addMaximum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMaximum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMaximum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMaximum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMaximumArg (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMaximumArg (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMaximumArg (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMaximumArg (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMaximumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMaximumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMaximumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMaximumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMDD (const std::vector< std::string > &variables, const std::vector< UniverseTransition > &transitions) override
void addMinimum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMinimum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMinimum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMinimum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMinimumArg (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMinimumArg (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMinimumArg (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMinimumArg (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMinimumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMinimumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMinimumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMinimumIndex (const std::vector< std::string > &variables, int startIndex, const std::string &index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const std::string &value) override
void addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addMultiDimensionalNoOverlap (const std::vector< std::vector< std::string >> &variables, const std::vector< std::vector< Universe::BigInteger >> &length) override
void addMultiDimensionalNoOverlap (const std::vector< std::vector< std::string >> &variables, const std::vector< std::vector< Universe::BigInteger >> &length, bool zeroIgnored) override
void addMultiDimensionalNoOverlapVariableLength (const std::vector< std::vector< std::string >> &variables, const std::vector< std::vector< std::string >> &length) override
void addMultiDimensionalNoOverlapVariableLength (const std::vector< std::vector< std::string >> &variables, const std::vector< std::vector< std::string >> &length, bool zeroIgnored) override
void addNoOverlap (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &length) override
void addNoOverlap (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &length, bool zeroIgnored) override
void addNoOverlapVariableLength (const std::vector< std::string > &variables, const std::vector< std::string > &length) override
void addNoOverlapVariableLength (const std::vector< std::string > &variables, const std::vector< std::string > &length, bool zeroIgnored) override
void addNotAllEqual (const std::vector< std::string > &variables) override
void addNValues (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &nb) override
void addNValues (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &nb) override
void addNValues (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addNValues (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addNValuesExcept (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &nb, const std::vector< Universe::BigInteger > &except) override
void addNValuesExcept (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &nb, const std::vector< Universe::BigInteger > &except) override
void addNValuesExcept (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set, const std::vector< Universe::BigInteger > &except) override
void addNValuesExcept (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max, const std::vector< Universe::BigInteger > &except) override
void addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseRelationalOperator op, const std::string &nb) override
void addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseRelationalOperator op, const Universe::BigInteger &nb) override
void addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &set) override
void addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addOrdered (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op) override
void addOrderedWithConstantLength (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &lengths, Universe::UniverseRelationalOperator op) override
void addOrderedWithVariableLength (const std::vector< std::string > &variables, const std::vector< std::string > &lengths, Universe::UniverseRelationalOperator op) override
void addPrecedence (const std::vector< std::string > &variables) override
void addPrecedence (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, bool covered) override
void addPrimitive (const std::string &variable, Universe::UniverseArithmeticOperator arithOp, const std::string &leftHandSide, Universe::UniverseRelationalOperator relOp, const std::string &rightHandSide) override
void addPrimitive (const std::string &variable, Universe::UniverseArithmeticOperator arithOp, const std::string &leftHandSide, Universe::UniverseRelationalOperator relOp, const Universe::BigInteger &rightHandSide) override
void addPrimitive (const std::string &variable, Universe::UniverseArithmeticOperator arithOp, const Universe::BigInteger &leftHandSide, Universe::UniverseRelationalOperator relOp, const std::string &rightHandSide) override
void addPrimitive (const std::string &variable, Universe::UniverseArithmeticOperator arithOp, const Universe::BigInteger &leftHandSide, Universe::UniverseRelationalOperator relOp, const Universe::BigInteger &rightHandSide) override
void addPrimitive (const std::string &variable, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addPrimitive (const std::string &variable, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addPrimitive (const std::string &variable, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addPrimitive (Universe::UniverseArithmeticOperator arithOp, const std::string &variable, const std::string &rightHandSide) override
void addRegular (const std::vector< std::string > &variables, const std::vector< UniverseTransition > &transitions, const std::string &startState, const std::vector< std::string > &finalStates) override
void addStretch (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::vector< Universe::BigInteger > &widthsMin, const std::vector< Universe::BigInteger > &widthsMax) override
void addStretch (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &values, const std::vector< Universe::BigInteger > &widthsMin, const std::vector< Universe::BigInteger > &widthsMax, const std::vector< std::vector< Universe::BigInteger >> &patterns) override
void addSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSum (const std::vector< std::string > &variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSum (const std::vector< std::string > &variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< std::string > &coefficients, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< std::string > &coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< std::string > &coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< std::string > &coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSumWithVariableCoefficients (const std::vector< std::string > &variables, const std::vector< std::string > &coefficients, Universe::UniverseRelationalOperator op, const std::string &rightVariable) override
void addSumWithVariableCoefficients (const std::vector< std::string > &variables, const std::vector< std::string > &coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger &value) override
void addSumWithVariableCoefficients (const std::vector< std::string > &variables, const std::vector< std::string > &coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > &values) override
void addSumWithVariableCoefficients (const std::vector< std::string > &variables, const std::vector< std::string > &coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void addSupport (const std::string &variable, const std::vector< Universe::BigInteger > &allowedValues, bool hasStar) override
void addSupport (const std::vector< std::string > &variableTuple, const std::vector< std::vector< Universe::BigInteger >> &allowedValues, bool hasStar) override
void addSupportSymbolic (const std::string &variable, const std::vector< std::string > &allowedValues, bool hasStar) override
void addSupportSymbolic (const std::vector< std::string > &variableTuple, const std::vector< std::vector< std::string >> &allowedValues, bool hasStar) override
void maximizeExpression (Universe::IUniverseIntensionConstraint *expression) override
void maximizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void maximizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void maximizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void maximizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void maximizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void maximizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeMaximum (const std::vector< std::string > &variables) override
void maximizeMaximum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeMinimum (const std::vector< std::string > &variables) override
void maximizeMinimum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeNValues (const std::vector< std::string > &variables) override
void maximizeNValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeProduct (const std::vector< std::string > &variables) override
void maximizeProduct (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeSum (const std::vector< std::string > &variables) override
void maximizeSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void maximizeVariable (const std::string &variable) override
void minimizeExpression (Universe::IUniverseIntensionConstraint *expression) override
void minimizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void minimizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void minimizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void minimizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void minimizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions) override
void minimizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > &expressions, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeMaximum (const std::vector< std::string > &variables) override
void minimizeMaximum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeMinimum (const std::vector< std::string > &variables) override
void minimizeMinimum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeNValues (const std::vector< std::string > &variables) override
void minimizeNValues (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeProduct (const std::vector< std::string > &variables) override
void minimizeProduct (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeSum (const std::vector< std::string > &variables) override
void minimizeSum (const std::vector< std::string > &variables, const std::vector< Universe::BigInteger > &coefficients) override
void minimizeVariable (const std::string &variable) override
void newVariable (const std::string &id, const std::vector< int > &values) override
void newVariable (const std::string &id, const std::vector< Universe::BigInteger > &values) override
void newVariable (const std::string &id, const Universe::BigInteger &min, const Universe::BigInteger &max) override
void newVariable (const std::string &id, int min, int max) override
void newVariableSymbolic (const std::string &id, const std::vector< std::string > &values) override
UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
UniverseSolverResult solveBoolean (const std::vector< UniverseAssumption< bool >> &assumptions) override
UniverseSolverResult solveDimacs (const std::vector< int > &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaPseudoBooleanSolver
UniverseJavaPseudoBooleanSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaPseudoBooleanSolver () override=default
void addAtLeast (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addAtLeast (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addAtLeast (const std::vector< int > &literals, int degree) override
void addAtMost (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addAtMost (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addAtMost (const std::vector< int > &literals, int degree) override
void addExactly (const std::vector< int > &literals, const std::vector< int > &coefficients, int degree) override
void addExactly (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, const Universe::BigInteger &degree) override
void addExactly (const std::vector< int > &literals, int degree) override
void addPseudoBoolean (const std::vector< int > &literals, const std::vector< Universe::BigInteger > &coefficients, bool moreThan, const BigInteger &degree) override
UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
UniverseSolverResult solveBoolean (const std::vector< UniverseAssumption< bool >> &assumptions) override
UniverseSolverResult solveDimacs (const std::vector< int > &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaSatSolver
UniverseJavaSatSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSatSolver () override=default
void addClause (const std::vector< int > &literals) override
Universe::UniverseSolverResult solve (const std::vector< UniverseAssumption< BigInteger >> &assumptions) override
Universe::UniverseSolverResult solveBoolean (const std::vector< UniverseAssumption< bool >> &assumptions) override
UniverseSolverResult solveDimacs (const std::vector< int > &assumptions) override
Public Member Functions inherited from Universe::UniverseJavaSolver
UniverseJavaSolver (easyjni::JavaClass *interface, easyjni::JavaObject object)
~UniverseJavaSolver () override=default
void addSearchListener (Universe::IUniverseSearchListener *listener) override
void decisionVariables (const std::vector< std::string > &variables) override
const std::map< std::string, Universe::IUniverseVariable * > & getVariablesMapping () override
void interrupt () override
bool isOptimization () override
void loadInstance (const std::string &filename) override
std::map< std::string, Universe::BigInteger > mapSolution () override
std::map< std::string, Universe::BigInteger > mapSolution (bool excludeAux) override
int nConstraints () override
int nVariables () override
void reset () override
void setLogFile (const std::string &filename) override
void setLogStream (std::ostream &stream) override
void setTimeout (long seconds) override
void setTimeoutMs (long mseconds) override
void setVerbosity (int level) override
std::vector< Universe::BigInteger > solution () override
UniverseSolverResult solve () override
UniverseSolverResult solve (const std::string &filename) override
Universe::IOptimizationSolver * toOptimizationSolver () override
Public Member Functions inherited from Universe::IUniverseSolver
virtual ~IUniverseSolver ()=default
Public Member Functions inherited from Universe::IUniverseSatSolver
~IUniverseSatSolver () override=default
virtual void addAllClauses (const std::vector< std::vector< int >> &clauses)
Public Member Functions inherited from Universe::IUniversePseudoBooleanSolver
~IUniversePseudoBooleanSolver () override=default
Static Protected Member Functions
static Universe::JavaList asList (const std::vector< std::string > &strings)
static Universe::JavaList asList (const std::vector< std::vector< std::string >> &matrix)
static Universe::JavaList asList (const std::vector< std::vector< Universe::BigInteger >> &matrix)
static Universe::JavaList asList (const std::vector< Universe::IUniverseIntensionConstraint * > &constraints)
static easyjni::JavaObject toJavaArithmeticOperator (Universe::UniverseArithmeticOperator op)
static easyjni::JavaObject toJavaBooleanOperator (Universe::UniverseBooleanOperator op)
static easyjni::JavaObject toJavaRelationalOperator (Universe::UniverseRelationalOperator op)
static easyjni::JavaObject toJavaSetBelongingOperator (Universe::UniverseSetBelongingOperator op)
Static Protected Member Functions inherited from Universe::UniverseJavaPseudoBooleanSolver
static Universe::JavaList asList (const std::vector< Universe::BigInteger > &integers, bool hasStar=false)
Static Protected Member Functions inherited from Universe::UniverseJavaSatSolver
static Universe::JavaList asList (const std::vector< int > &integers)
Static Protected Member Functions inherited from Universe::UniverseJavaSolver
template<typename T >
static Universe::JavaList toJavaAssumptions (std::vector< Universe::UniverseAssumption< T >> assumptions, std::function< easyjni::JavaObject(T)> toJavaObject)
static Universe::UniverseSolverResult toUniverseSolverResult (easyjni::JavaObject javaResult)
Additional Inherited Members
Protected Attributes inherited from Universe::UniverseJavaSolver
easyjni::JavaClass * interface
std::map< std::string, Universe::IUniverseVariable * > mapping
easyjni::JavaObject object
Detailed Description
The UniverseJavaCspSolver class defines an adapter for an IUniverseCspSolver written in Java (and implementing the JUniverse interface). The solver is run through the Java Native Interface (JNI).
Definition at line 45 of file UniverseJavaCspSolver.hpp.
Constructor & Destructor Documentation
UniverseJavaCspSolver()
UniverseJavaCspSolver::UniverseJavaCspSolver (easyjni::JavaClass * interface, const easyjni::JavaObject & object)
Creates a UniverseJavaCspSolver.
Parameters
interface The Java interface corresponding to IUniverseCspSolver.
object The Java object to adapt.
Definition at line 55 of file UniverseJavaCspSolver.cpp.
~UniverseJavaCspSolver()
Universe::UniverseJavaCspSolver::~UniverseJavaCspSolver () override default
Destroys this UniverseJavaCspSolver.
Member Function Documentation
addAllDifferent() [1/2]
void UniverseJavaCspSolver::addAllDifferent (const std::vector< std::string > & variables) override virtual
Adds to this solver an all-different constraint.
Parameters
variables The variables that should all be different.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 186 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAllDifferent() [2/2]
void UniverseJavaCspSolver::addAllDifferent (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an all-different constraint.
Parameters
variables The variables that should all be different.
except The values not to consider in the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 192 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAllDifferentIntension()
void UniverseJavaCspSolver::addAllDifferentIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints) override virtual
Adds to this solver an all-different constraint.
Parameters
intensionConstraints The intension constraints that should all be different.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 224 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAllDifferentList() [1/2]
void UniverseJavaCspSolver::addAllDifferentList (const std::vector< std::vector< std::string >> & variableLists) override virtual
Adds to this solver an all-different constraint.
Parameters
variableLists The lists of variables that should all be different.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 213 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAllDifferentList() [2/2]
void UniverseJavaCspSolver::addAllDifferentList (const std::vector< std::vector< std::string >> & variableLists, const std::vector< std::vector< Universe::BigInteger >> & except) override virtual
Adds to this solver an all-different constraint.
Parameters
variableLists The lists of variables that should all be different.
except The values not to consider in the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 219 of file UniverseJavaCspSolver.cpp.
addAllDifferentMatrix() [1/2]
void UniverseJavaCspSolver::addAllDifferentMatrix (const std::vector< std::vector< std::string >> & variableMatrix) override virtual
Adds to this solver an all-different constraint.
Parameters
variableMatrix The matrix of variables that should all be different.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 199 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAllDifferentMatrix() [2/2]
void UniverseJavaCspSolver::addAllDifferentMatrix (const std::vector< std::vector< std::string >> & variableMatrix, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an all-different constraint.
Parameters
variableMatrix The matrix of variables that should all be different.
except The values not to consider in the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 205 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAllEqual()
void UniverseJavaCspSolver::addAllEqual (const std::vector< std::string > & variables) override virtual
Adds to this solver an all-equal constraint.
Parameters
variables The variables that should all be equal.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1783 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAllEqualIntension()
void UniverseJavaCspSolver::addAllEqualIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an all-equal constraint.
Parameters
expressions The expressions that should all be equal.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1789 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addAmong() [1/2]
void UniverseJavaCspSolver::addAmong (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::string & count) override virtual
Adds to this solver an among constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
count The variable encoding the number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 357 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addAmong() [2/2]
void UniverseJavaCspSolver::addAmong (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const Universe::BigInteger & count) override virtual
Adds to this solver an among constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
count The number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 347 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addAtLeast()
void UniverseJavaCspSolver::addAtLeast (const std::vector< std::string > & variables, const Universe::BigInteger & value, const Universe::BigInteger & count) override virtual
Adds to this solver an at-least constraint.
Parameters
variables The variables to count the assignments of.
value The value to count the assignments of.
count The minimum number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 318 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addAtMost()
void UniverseJavaCspSolver::addAtMost (const std::vector< std::string > & variables, const Universe::BigInteger & value, const Universe::BigInteger & count) override virtual
Adds to this solver an at-most constraint.
Parameters
variables The variables to count the assignments of.
value The value to count the assignments of.
count The maximum number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 367 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addBiDimensionalNoOverlap() [1/2]
void UniverseJavaCspSolver::addBiDimensionalNoOverlap (const std::vector< std::string > & xVariables, const std::vector< std::string > & yVariables, const std::vector< std::string > & xLength, const std::vector< Universe::BigInteger > & yLength) override virtual
Adds to this solver a no-overlap constraint.
Parameters
xVariables The variables appearing in the constraint on the x-axis.
yVariables The variables appearing in the constraint on the y-axis.
xLength The variables for the lengths associated to the variables on the x-axis.
yLength The lengths associated to the variables on the y-axis.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1705 of file UniverseJavaCspSolver.cpp.
addBiDimensionalNoOverlap() [2/2]
void UniverseJavaCspSolver::addBiDimensionalNoOverlap (const std::vector< std::string > & xVariables, const std::vector< std::string > & yVariables, const std::vector< std::string > & xLength, const std::vector< Universe::BigInteger > & yLength, bool zeroIgnored) override virtual
Adds to this solver a no-overlap constraint.
Parameters
xVariables The variables appearing in the constraint on the x-axis.
yVariables The variables appearing in the constraint on the y-axis.
xLength The variables for the lengths associated to the variables on the x-axis.
yLength The lengths associated to the variables on the y-axis.
zeroIgnored Whether 0-lengths should be ignored.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1712 of file UniverseJavaCspSolver.cpp.
addBinPacking() [1/4]
void UniverseJavaCspSolver::addBinPacking (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, Universe::UniverseRelationalOperator op, const std::string & variable) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
op The operator used to ensure the capacity of the bins.
variable The variable encoding the bins capacity.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 590 of file UniverseJavaCspSolver.cpp.
addBinPacking() [2/4]
void UniverseJavaCspSolver::addBinPacking (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
op The operator used to ensure the capacity of the bin.
value The value of the bins capacity.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 584 of file UniverseJavaCspSolver.cpp.
addBinPacking() [3/4]
void UniverseJavaCspSolver::addBinPacking (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
op The operator used to ensure the capacity of the bins.
set The allowed capacities for the bins.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 603 of file UniverseJavaCspSolver.cpp.
addBinPacking() [4/4]
void UniverseJavaCspSolver::addBinPacking (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
op The operator used to ensure the capacity of the bins.
min The minimum capacity of the bins.
max The maximum capacity of the bins.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 596 of file UniverseJavaCspSolver.cpp.
addBinPackingWithConstantCapacities()
void UniverseJavaCspSolver::addBinPackingWithConstantCapacities (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, const std::vector< Universe::BigInteger > & capacities, bool loads) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
capacities The capacities of each bin.
loads Whether bin loads should be computed.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 609 of file UniverseJavaCspSolver.cpp.
addBinPackingWithVariableCapacities()
void UniverseJavaCspSolver::addBinPackingWithVariableCapacities (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & sizes, const std::vector< std::string > & capacities, bool loads) override virtual
Adds to this solver a bin-packing constraint.
Parameters
variables The variables appearing in the constraint.
sizes The sizes of the elements to pack.
capacities The variables encoding the capacities of each bin.
loads Whether bin loads should be computed.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 616 of file UniverseJavaCspSolver.cpp.
addCardinalityWithConstantValuesAndConstantCounts()
void UniverseJavaCspSolver::addCardinalityWithConstantValuesAndConstantCounts (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::vector< Universe::BigInteger > & occurs, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The assignable values to count.
occurs The number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 253 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addCardinalityWithConstantValuesAndConstantIntervalCounts()
void UniverseJavaCspSolver::addCardinalityWithConstantValuesAndConstantIntervalCounts (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::vector< Universe::BigInteger > & occursMin, const std::vector< Universe::BigInteger > & occursMax, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The assignable values to count.
occursMin The minimum number of times each value can be assigned.
occursMax The maximum number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 264 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addCardinalityWithConstantValuesAndVariableCounts()
void UniverseJavaCspSolver::addCardinalityWithConstantValuesAndVariableCounts (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::vector< std::string > & occurs, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The assignable values to count.
occurs The variables encoding the number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 276 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addCardinalityWithVariableValuesAndConstantCounts()
void UniverseJavaCspSolver::addCardinalityWithVariableValuesAndConstantCounts (const std::vector< std::string > & variables, const std::vector< std::string > & values, const std::vector< Universe::BigInteger > & occurs, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the assignable values to count.
occurs The number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 286 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addCardinalityWithVariableValuesAndConstantIntervalCounts()
void UniverseJavaCspSolver::addCardinalityWithVariableValuesAndConstantIntervalCounts (const std::vector< std::string > & variables, const std::vector< std::string > & values, const std::vector< Universe::BigInteger > & occursMin, const std::vector< Universe::BigInteger > & occursMax, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the assignable values to count.
occursMin The minimum number of times each value can be assigned.
occursMax The maximum number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 296 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addCardinalityWithVariableValuesAndVariableCounts()
void UniverseJavaCspSolver::addCardinalityWithVariableValuesAndVariableCounts (const std::vector< std::string > & variables, const std::vector< std::string > & values, const std::vector< std::string > & occurs, bool closed) override virtual
Adds to this solver a cardinality constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the assignable values to count.
occurs The variables encoding the number of times each value can be assigned.
closed Whether only the values in value can be assigned to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 308 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addChannel() [1/3]
void UniverseJavaCspSolver::addChannel (const std::vector< std::string > & variables, int startIndex) override virtual
Adds to this solver a channel constraint.
Parameters
variables The variables appearing in the constraint.
startIndex The index at which the constraint starts.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 231 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addChannel() [2/3]
void UniverseJavaCspSolver::addChannel (const std::vector< std::string > & variables, int startIndex, const std::string & value) override virtual
Adds to this solver a channel constraint.
Parameters
variables The variables among which exactly one should be satisfied starting from the given index.
startIndex The index at which the constraint starts.
value The variable containing the index of the satisfied variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 237 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addChannel() [3/3]
void UniverseJavaCspSolver::addChannel (const std::vector< std::string > & variables, int startIndex, const std::vector< std::string > & otherVariables, int otherStartIndex) override virtual
Adds to this solver a channel constraint.
Parameters
variables The variables appearing in the constraint.
startIndex The index at which the constraint starts on the first vector of variables.
otherVariables The variables with which to channel the variables of the first vector.
otherStartIndex The index at which the constraint starts on the second vector of variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 244 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addCircuit() [1/3]
void UniverseJavaCspSolver::addCircuit (const std::vector< std::string > & variables, int startIndex) override virtual
Adds to this solver a circuit constraint.
Parameters
variables The variables representing the circuit.
startIndex The index of the variable at which the circuit starts.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2027 of file UniverseJavaCspSolver.cpp.
addCircuit() [2/3]
void UniverseJavaCspSolver::addCircuit (const std::vector< std::string > & variables, int startIndex, const std::string & size) override virtual
Adds to this solver a circuit constraint.
Parameters
variables The variables representing the circuit.
startIndex The index of the variable at which the circuit starts.
size The variable encoding the size of the expected circuit.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2035 of file UniverseJavaCspSolver.cpp.
addCircuit() [3/3]
void UniverseJavaCspSolver::addCircuit (const std::vector< std::string > & variables, int startIndex, const Universe::BigInteger & size) override virtual
Adds to this solver a circuit constraint.
Parameters
variables The variables representing the circuit.
startIndex The index of the variable at which the circuit starts.
size The size of the expected circuit.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2031 of file UniverseJavaCspSolver.cpp.
addClause()
void UniverseJavaCspSolver::addClause (const std::vector< std::string > & positive, const std::vector< std::string > & negative) override virtual
Adds to this solver a clause constraint.
Parameters
positive The (Boolean) variables appearing positively in the clause.
negative The (Boolean) variables appearing negatively in the clause.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 138 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addConflicts() [1/2]
void UniverseJavaCspSolver::addConflicts (const std::string & variable, const std::vector< Universe::BigInteger > & forbiddenValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the conflicts of a variable.
Parameters
variable The variable for which the conflicts are given.
forbiddenValues The values forbidden for the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1284 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addConflicts() [2/2]
void UniverseJavaCspSolver::addConflicts (const std::vector< std::string > & variableTuple, const std::vector< std::vector< Universe::BigInteger >> & forbiddenValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the conflicts of a tuple of variables.
Parameters
variableTuple The tuple of variables for which the conflicts are given.
forbiddenValues The values forbidden for the tuple variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1296 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addConflictsSymbolic() [1/2]
void UniverseJavaCspSolver::addConflictsSymbolic (const std::string & variable, const std::vector< std::string > & forbiddenValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the conflicts of a variable.
Parameters
variable The variable for which the conflicts are given.
forbiddenValues The values forbidden for the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1292 of file UniverseJavaCspSolver.cpp.
addConflictsSymbolic() [2/2]
void UniverseJavaCspSolver::addConflictsSymbolic (const std::vector< std::string > & variableTuple, const std::vector< std::vector< std::string >> & forbiddenValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the conflicts of a tuple of variables.
Parameters
variableTuple The tuple of variables for which the conflicts are given.
forbiddenValues The values forbidden for the tuple variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1305 of file UniverseJavaCspSolver.cpp.
addCountIntensionWithConstantValues() [1/4]
void UniverseJavaCspSolver::addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & values, Universe::UniverseRelationalOperator op, const std::string & count) override virtual
Adds to this solver a count constraint.
Parameters
expressions The expressions to count the assignments of.
values The values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The variable encoding the number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 457 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountIntensionWithConstantValues() [2/4]
void UniverseJavaCspSolver::addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & values, Universe::UniverseRelationalOperator op, const Universe::BigInteger & count) override virtual
Adds to this solver a count constraint.
Parameters
expressions The expressions to count the assignments of.
values The values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The variable encoding the number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 445 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountIntensionWithConstantValues() [3/4]
void UniverseJavaCspSolver::addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a count constraint.
Parameters
expressions The expressions to count the assignments of.
values The values to count the assignments of.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed numbers of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 476 of file UniverseJavaCspSolver.cpp.
addCountIntensionWithConstantValues() [4/4]
void UniverseJavaCspSolver::addCountIntensionWithConstantValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a count constraint.
Parameters
expressions The expressions to count the assignments of.
values The values to count the assignments of.
op The operator to use to check whether the number of assignments is within a range.
min The minimum number of times the value can be assigned among the variables.
max The maximum number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 469 of file UniverseJavaCspSolver.cpp.
addCountWithConstantValues() [1/4]
void UniverseJavaCspSolver::addCountWithConstantValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, Universe::UniverseRelationalOperator op, const std::string & count) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The variable encoding the number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 388 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountWithConstantValues() [2/4]
void UniverseJavaCspSolver::addCountWithConstantValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, Universe::UniverseRelationalOperator op, const Universe::BigInteger & count) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 377 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountWithConstantValues() [3/4]
void UniverseJavaCspSolver::addCountWithConstantValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed numbers of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 405 of file UniverseJavaCspSolver.cpp.
addCountWithConstantValues() [4/4]
void UniverseJavaCspSolver::addCountWithConstantValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The values to count the assignments of.
op The operator to use to check whether the number of assignments is within a range.
min The minimum number of times the value can be assigned among the variables.
max The maximum number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 399 of file UniverseJavaCspSolver.cpp.
addCountWithVariableValues() [1/4]
void UniverseJavaCspSolver::addCountWithVariableValues (const std::vector< std::string > & variables, const std::vector< std::string > & values, Universe::UniverseRelationalOperator op, const std::string & count) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The variable encoding the number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 422 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountWithVariableValues() [2/4]
void UniverseJavaCspSolver::addCountWithVariableValues (const std::vector< std::string > & variables, const std::vector< std::string > & values, Universe::UniverseRelationalOperator op, const Universe::BigInteger & count) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the values to count the assignments of.
op The operator to use to compare the number of assignments to their expected count.
count The number of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 411 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCountWithVariableValues() [3/4]
void UniverseJavaCspSolver::addCountWithVariableValues (const std::vector< std::string > & variables, const std::vector< std::string > & values, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the values to count the assignments of.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed numbers of times the values can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 439 of file UniverseJavaCspSolver.cpp.
addCountWithVariableValues() [4/4]
void UniverseJavaCspSolver::addCountWithVariableValues (const std::vector< std::string > & variables, const std::vector< std::string > & values, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a count constraint.
Parameters
variables The variables to count the assignments of.
values The variables encoding the values to count the assignments of.
op The operator to use to check whether the number of assignments is within a range.
min The minimum number of times the value can be assigned among the variables.
max The maximum number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 433 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsConstantHeights() [1/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 662 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsConstantHeights() [2/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 635 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsConstantHeights() [3/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 701 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsConstantHeights() [4/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 684 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsConstantHeights() [5/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 649 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsConstantHeights() [6/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 622 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsConstantHeights() [7/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 693 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsConstantHeights() [8/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 676 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsVariableHeights() [1/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variable encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 750 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsVariableHeights() [2/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variable encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 723 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsVariableHeights() [3/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variable encoding the heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 789 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsVariableHeights() [4/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variable encoding the heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 772 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsVariableHeights() [5/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The variable encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 737 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsVariableHeights() [6/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The variable encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 710 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeConstantLengthsVariableHeights() [7/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The variable encoding the heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 781 of file UniverseJavaCspSolver.cpp.
addCumulativeConstantLengthsVariableHeights() [8/8]
void UniverseJavaCspSolver::addCumulativeConstantLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< Universe::BigInteger > & lengths, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The lengths of the tasks to assign.
heights The variable encoding the heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 764 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsConstantHeights() [1/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 899 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsConstantHeights() [2/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 811 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsConstantHeights() [3/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 863 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsConstantHeights() [4/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 846 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsConstantHeights() [5/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 825 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsConstantHeights() [6/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 798 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsConstantHeights() [7/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 855 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsConstantHeights() [8/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsConstantHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< Universe::BigInteger > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 838 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsVariableHeights() [1/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variables encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 926 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsVariableHeights() [2/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variables encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 885 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsVariableHeights() [3/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variables encoding the heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 965 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsVariableHeights() [4/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & ends, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
ends The variables encoding the ends of the resources.
heights The variables encoding the heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 948 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsVariableHeights() [5/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The variables encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The variable encoding the value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 913 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsVariableHeights() [6/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & heights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The variables encoding the heights of the tasks to assign.
op The operator to compare the cumulative use with.
value The value for the cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 872 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addCumulativeVariableLengthsVariableHeights() [7/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The variables encoding the heights of the tasks to assign.
op The operator to use to check whether the number of assignments is within a set.
set The set containing the allowed cumulative uses.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 957 of file UniverseJavaCspSolver.cpp.
addCumulativeVariableLengthsVariableHeights() [8/8]
void UniverseJavaCspSolver::addCumulativeVariableLengthsVariableHeights (const std::vector< std::string > & origins, const std::vector< std::string > & lengths, const std::vector< std::string > & heights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a cumulative constraint.
Parameters
origins The variables encoding the origins of the resources.
lengths The variables encoding the lengths of the tasks to assign.
heights The variables encoding the heights of the tasks to assign.
op The operator to use to check whether the cumulative use is within a range.
min The minimum cumulative use.
max The maximum cumulative use.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 940 of file UniverseJavaCspSolver.cpp.
addElement() [1/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const std::string & variable) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables among which to look for the value.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The relational operator used to compare the value with those assigned to the variables.
variable The variable whose value is to be looked for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1177 of file UniverseJavaCspSolver.cpp.
addElement() [2/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables among which to look for the value.
startIndex The index at which to start looking for the value.
index The index at which the value appears in the variables.
op The relational operator used to compare the value with those assigned to the variables.
value The value to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1172 of file UniverseJavaCspSolver.cpp.
addElement() [3/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables among which to look for the value.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The operator used to check whether a variable is assigned in the set.
set The set of values to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1188 of file UniverseJavaCspSolver.cpp.
addElement() [4/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables among which to look for the value.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The operator used to check whether a variable is assigned in the range.
min The minimum value of the range.
max The maximum value of the range.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1182 of file UniverseJavaCspSolver.cpp.
addElement() [5/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used to compare the value with those assigned to the variables.
value The variable encoding the value to look for among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1133 of file UniverseJavaCspSolver.cpp.
addElement() [6/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used to compare the value with those assigned to the variables.
value The value to look for among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1128 of file UniverseJavaCspSolver.cpp.
addElement() [7/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables appearing in the constraint.
op The operator used to check whether a variable is assigned in the set.
set The set of values to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1143 of file UniverseJavaCspSolver.cpp.
addElement() [8/8]
void UniverseJavaCspSolver::addElement (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an element constraint.
Parameters
variables The variables appearing in the constraint.
op The operator used to check whether a variable is assigned in the range.
min The minimum value of the range.
max The maximum value of the range.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1138 of file UniverseJavaCspSolver.cpp.
addElementConstantMatrix() [1/4]
void UniverseJavaCspSolver::addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of values among which the value must appear.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The relational operator used to compare the value with those assigned to the variables.
value The variable whose value is to be looked for inside the matrix.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1201 of file UniverseJavaCspSolver.cpp.
addElementConstantMatrix() [2/4]
void UniverseJavaCspSolver::addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of values among which the value must appear.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The relational operator used to compare the value with those assigned to the variables.
value The value to look for inside the matrix.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1194 of file UniverseJavaCspSolver.cpp.
addElementConstantMatrix() [3/4]
void UniverseJavaCspSolver::addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of values among which the value must appear.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The operator used to check whether a variable is assigned in the set.
set The set of values to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1215 of file UniverseJavaCspSolver.cpp.
addElementConstantMatrix() [4/4]
void UniverseJavaCspSolver::addElementConstantMatrix (const std::vector< std::vector< Universe::BigInteger >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of values among which the value must appear.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The operator used to check whether a variable is assigned in the range.
min The minimum value of the range.
max The maximum value of the range.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1208 of file UniverseJavaCspSolver.cpp.
addElementConstantValues() [1/4]
void UniverseJavaCspSolver::addElementConstantValues (const std::vector< Universe::BigInteger > & values, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const std::string & variable) override virtual
Adds to this solver an element constraint.
Parameters
values The values among which to look for the variable.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The relational operator used to compare the value with those assigned to the variables.
variable The variable whose value is to be looked for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1154 of file UniverseJavaCspSolver.cpp.
addElementConstantValues() [2/4]
void UniverseJavaCspSolver::addElementConstantValues (const std::vector< Universe::BigInteger > & values, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver an element constraint.
Parameters
values The values among which to look for the variable.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The relational operator used to compare the value with those assigned to the variables.
value The value to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1148 of file UniverseJavaCspSolver.cpp.
addElementConstantValues() [3/4]
void UniverseJavaCspSolver::addElementConstantValues (const std::vector< Universe::BigInteger > & values, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an element constraint.
Parameters
values The values among which to look for the variable.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The operator used to check whether a variable is assigned in the set.
set The set of values to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1166 of file UniverseJavaCspSolver.cpp.
addElementConstantValues() [4/4]
void UniverseJavaCspSolver::addElementConstantValues (const std::vector< Universe::BigInteger > & values, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an element constraint.
Parameters
values The values among which to look for the variable.
startIndex The index at which to start looking for the variable.
index The index at which the variable appears in the values.
op The operator used to check whether a variable is assigned in the range.
min The minimum value of the range.
max The maximum value of the range.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1160 of file UniverseJavaCspSolver.cpp.
addElementMatrix() [1/4]
void UniverseJavaCspSolver::addElementMatrix (const std::vector< std::vector< std::string >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of variables among which the value must be assigned.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The relational operator used to compare the value with those assigned to the variables.
value The variable whose value is to be looked for inside the matrix.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1228 of file UniverseJavaCspSolver.cpp.
addElementMatrix() [2/4]
void UniverseJavaCspSolver::addElementMatrix (const std::vector< std::vector< std::string >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of variables among which the value must be assigned.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The relational operator used to compare the value with those assigned to the variables.
value The variable whose value is to be looked for inside the matrix.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1222 of file UniverseJavaCspSolver.cpp.
addElementMatrix() [3/4]
void UniverseJavaCspSolver::addElementMatrix (const std::vector< std::vector< std::string >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of variables among which the value must be assigned.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The operator used to check whether a variable is assigned in the set.
set The set of values to look for.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1241 of file UniverseJavaCspSolver.cpp.
addElementMatrix() [4/4]
void UniverseJavaCspSolver::addElementMatrix (const std::vector< std::vector< std::string >> & matrix, int startRowIndex, const std::string & rowIndex, int startColIndex, const std::string & colIndex, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an element constraint.
Parameters
matrix The matrix of variables among which the value must be assigned.
startRowIndex The index of the row starting from which the value must appear.
rowIndex The variable encoding the index of the row at which the value appears.
startColIndex The index of the column starting from which the value must appear.
colIndex The variable encoding the index of the column at which the value appears.
op The operator used to check whether a variable is assigned in the range.
min The minimum value of the range.
max The maximum value of the range.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1234 of file UniverseJavaCspSolver.cpp.
addExactly() [1/2]
void UniverseJavaCspSolver::addExactly (const std::vector< std::string > & variables, const Universe::BigInteger & value, const std::string & count) override virtual
Adds to this solver an exactly constraint.
Parameters
variables The variables to count the assignments of.
value The value to count the assignments of.
count The variable encoding the number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 338 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addExactly() [2/2]
void UniverseJavaCspSolver::addExactly (const std::vector< std::string > & variables, const Universe::BigInteger & value, const Universe::BigInteger & count) override virtual
Adds to this solver an exactly constraint.
Parameters
variables The variables to count the assignments of.
value The value to count the assignments of.
count The number of times the value can be assigned among the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 328 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addFlow() [1/5]
void UniverseJavaCspSolver::addFlow (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & balance, const std::vector< std::vector< Universe::BigInteger >> & edges) override virtual
Adds to this solver a flow constraint.
Parameters
variables The variable encoding the flow.
balance The balance in the network, i.e., the difference between input and output flows.
edges The edges in the network.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2050 of file UniverseJavaCspSolver.cpp.
addFlow() [2/5]
void UniverseJavaCspSolver::addFlow (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & balance, const std::vector< std::vector< Universe::BigInteger >> & edges, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator op, const std::string & totalCost) override virtual
Adds to this solver a flow constraint.
Parameters
variables The variable encoding the flow.
balance The balance in the network, i.e., the difference between input and output flows.
edges The edges in the network.
weights The weights on the edges of the network.
op The operator comparing the total cost.
totalCost The variable encoding the total cost of the flow.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2062 of file UniverseJavaCspSolver.cpp.
addFlow() [3/5]
void UniverseJavaCspSolver::addFlow (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & balance, const std::vector< std::vector< Universe::BigInteger >> & edges, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator op, const Universe::BigInteger & totalCost) override virtual
Adds to this solver a flow constraint.
Parameters
variables The variable encoding the flow.
balance The balance in the network, i.e., the difference between input and output flows.
edges The edges in the network.
weights The weights on the edges of the network.
op The operator comparing the total cost.
totalCost The total cost of the flow.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2055 of file UniverseJavaCspSolver.cpp.
addFlow() [4/5]
void UniverseJavaCspSolver::addFlow (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & balance, const std::vector< std::vector< Universe::BigInteger >> & edges, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a flow constraint.
Parameters
variables The variable encoding the flow.
balance The balance in the network, i.e., the difference between input and output flows.
edges The edges in the network.
weights The weights on the edges of the network.
op The operator comparing the total cost.
set The possible values for the total cost.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2077 of file UniverseJavaCspSolver.cpp.
addFlow() [5/5]
void UniverseJavaCspSolver::addFlow (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & balance, const std::vector< std::vector< Universe::BigInteger >> & edges, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a flow constraint.
Parameters
variables The variable encoding the flow.
balance The balance in the network, i.e., the difference between input and output flows.
edges The edges in the network.
weights The weights on the edges of the network.
op The operator comparing the total cost.
min The minimum total cost of the flow.
max The maximum total cost of the flow.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2069 of file UniverseJavaCspSolver.cpp.
addInstantiation() [1/5]
void UniverseJavaCspSolver::addInstantiation (const std::string & variable, const std::string & value) override virtual
Adds to this solver an instantiation constraint.
Parameters
variable The variable to assign.
value The value to assign to the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 113 of file UniverseJavaCspSolver.cpp.
addInstantiation() [2/5]
void UniverseJavaCspSolver::addInstantiation (const std::string & variable, const Universe::BigInteger & value) override virtual
Adds to this solver an instantiation constraint.
Parameters
variable The variable to assign.
value The value to assign to the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 105 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
addInstantiation() [3/5]
void UniverseJavaCspSolver::addInstantiation (const std::string & variable, int value) override virtual
Adds to this solver an instantiation constraint.
Parameters
variable The variable to assign.
value The value to assign to the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 98 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addInstantiation() [4/5]
void UniverseJavaCspSolver::addInstantiation (const std::vector< std::string > & variables, const std::vector< int > & values) override virtual
Adds to this solver an instantiation constraint.
Parameters
variables The variables to assign.
values The values to assign to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 117 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), asList(), and Universe::UniverseJavaSolver::interface.
addInstantiation() [5/5]
void UniverseJavaCspSolver::addInstantiation (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver an instantiation constraint.
Parameters
variables The variables to assign.
values The values to assign to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 125 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addInstantiationSymbolic()
void UniverseJavaCspSolver::addInstantiationSymbolic (const std::vector< std::string > & variables, const std::vector< std::string > & values) override virtual
Adds to this solver an instantiation constraint.
Parameters
variables The variables to assign.
values The values to assign to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 133 of file UniverseJavaCspSolver.cpp.
addIntension()
void UniverseJavaCspSolver::addIntension (Universe::IUniverseIntensionConstraint * constr) override virtual
Adds to this solver an intension constraint.
Parameters
constr The user-friendly representation of the constraint to add.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1310 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addKnapsack() [1/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const std::string & wVariable, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const std::string & pVariable) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wVariable The variable encoding the total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pVariable The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1018 of file UniverseJavaCspSolver.cpp.
addKnapsack() [2/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const std::string & wVariable, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger & pValue) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wVariable The variable encoding the total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pValue The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1010 of file UniverseJavaCspSolver.cpp.
addKnapsack() [3/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const std::string & wVariable, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > & pSet) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wVariable The variable encoding the total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pSet The allowed total profits of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1035 of file UniverseJavaCspSolver.cpp.
addKnapsack() [4/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const std::string & wVariable, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger & pMin, const Universe::BigInteger & pMax) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wVariable The variable encoding the total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pMin The minimum profit of the knapsack.
pMax The maximum profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1026 of file UniverseJavaCspSolver.cpp.
addKnapsack() [5/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger & wValue, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const std::string & pVariable) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wValue The total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pVariable The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 984 of file UniverseJavaCspSolver.cpp.
addKnapsack() [6/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger & wValue, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger & pValue) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wValue The total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pValue The total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 976 of file UniverseJavaCspSolver.cpp.
addKnapsack() [7/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger & wValue, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > & pSet) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wValue The total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pSet The allowed total profits of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1001 of file UniverseJavaCspSolver.cpp.
addKnapsack() [8/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseRelationalOperator wOperator, const Universe::BigInteger & wValue, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger & pMin, const Universe::BigInteger & pMax) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wValue The total weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pMin The minimum profit of the knapsack.
pMax The maximum profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 992 of file UniverseJavaCspSolver.cpp.
addKnapsack() [9/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > & wSet, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const std::string & pVariable) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wSet The allowed total weights of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pVariable The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1087 of file UniverseJavaCspSolver.cpp.
addKnapsack() [10/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > & wSet, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger & pValue) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wSet The allowed total weights of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pValue The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1078 of file UniverseJavaCspSolver.cpp.
addKnapsack() [11/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > & wSet, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > & pSet) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wSet The allowed total weights of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pSet The allowed total profits of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1106 of file UniverseJavaCspSolver.cpp.
addKnapsack() [12/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const std::vector< Universe::BigInteger > & wSet, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger & pMin, const Universe::BigInteger & pMax) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wSet The allowed total weights of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pMin The minimum profit of the knapsack.
pMax The maximum profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1096 of file UniverseJavaCspSolver.cpp.
addKnapsack() [13/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger & wMin, const Universe::BigInteger & wMax, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const std::string & pVariable) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wMin The minimum weight of the knapsack.
wMax The maximum weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pVariable The variable encoding the total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1052 of file UniverseJavaCspSolver.cpp.
addKnapsack() [14/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger & wMin, const Universe::BigInteger & wMax, const std::vector< Universe::BigInteger > & profits, Universe::UniverseRelationalOperator pOperator, const Universe::BigInteger & pValue) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wMin The minimum weight of the knapsack.
wMax The maximum weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pValue The total profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1044 of file UniverseJavaCspSolver.cpp.
addKnapsack() [15/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger & wMin, const Universe::BigInteger & wMax, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const std::vector< Universe::BigInteger > & pSet) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wMin The minimum weight of the knapsack.
wMax The maximum weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pSet The allowed total profits of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1069 of file UniverseJavaCspSolver.cpp.
addKnapsack() [16/16]
void UniverseJavaCspSolver::addKnapsack (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & weights, Universe::UniverseSetBelongingOperator wOperator, const Universe::BigInteger & wMin, const Universe::BigInteger & wMax, const std::vector< Universe::BigInteger > & profits, Universe::UniverseSetBelongingOperator pOperator, const Universe::BigInteger & pMin, const Universe::BigInteger & pMax) override virtual
Adds to this solver a knapsack constraint.
Parameters
variables The variables appearing in the constraint.
weights The weights of the elements to put in the knapsack.
wOperator The operator for comparing the weight of the knapsack.
wMin The minimum weight of the knapsack.
wMax The maximum weight of the knapsack.
profits The profits of the elements to put in the knapsack.
pOperator The operator for comparing the profit of the knapsack.
pMin The minimum profit of the knapsack.
pMax The maximum profit of the knapsack.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1060 of file UniverseJavaCspSolver.cpp.
addLex() [1/2]
void UniverseJavaCspSolver::addLex (const std::vector< std::vector< std::string >> & tuples, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver a lex constraint.
Parameters
tuples The tuple of variables that should be lexicographically ordered.
op The relational operator defining the order of the tuples.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1801 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addLex() [2/2]
void UniverseJavaCspSolver::addLex (const std::vector< std::vector< std::string >> & variables, const std::vector< std::vector< Universe::BigInteger >> & limit, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver a lex constraint.
Parameters
variables The variables that should be lexicographically ordered.
limit The limits of the constraint.
op The relational operator defining the order of the tuples.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1809 of file UniverseJavaCspSolver.cpp.
addLexMatrix()
void UniverseJavaCspSolver::addLexMatrix (const std::vector< std::vector< std::string >> & matrix, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver a lex-matrix constraint.
Parameters
matrix The matrix of variables that should be lexicographically ordered.
op The relational operator defining the order in the matrix.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1815 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addLogical() [1/4]
void UniverseJavaCspSolver::addLogical (const std::string & variable, bool equiv, Universe::UniverseBooleanOperator op, const std::vector< std::string > & variables) override virtual
Adds to this solver a logical constraint.
Parameters
variable The (Boolean) variable whose assignment depends on the truth value of the logical operation.
equiv Whether variable must be equivalent to the truth value of the logical operation.
op The Boolean operator to apply on the variables.
variables The (Boolean) variables on which the operator is applied.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 154 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addLogical() [2/4]
void UniverseJavaCspSolver::addLogical (const std::string & variable, const std::string & left, Universe::UniverseRelationalOperator op, const std::string & right) override virtual
Adds to this solver a logical constraint.
Parameters
variable The (Boolean) variable whose assignment depends on the truth value of the comparison between left and right.
left The variable on the left-hand side of the comparison.
op The relational operator used to compare left and right.
right The variable on the right-hand side of the comparison.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 175 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addLogical() [3/4]
void UniverseJavaCspSolver::addLogical (const std::string & variable, const std::string & left, Universe::UniverseRelationalOperator op, const Universe::BigInteger & right) override virtual
Adds to this solver a logical constraint.
Parameters
variable The (Boolean) variable whose assignment depends on the truth value of the comparison between left and right.
left The variable on the left-hand side of the comparison.
op The relational operator used to compare left and right.
right The value on the right-hand side of the comparison.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 164 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addLogical() [4/4]
void UniverseJavaCspSolver::addLogical (Universe::UniverseBooleanOperator op, const std::vector< std::string > & variables) override virtual
Adds to this solver a logical constraint.
Parameters
op The Boolean operator to apply on the variables.
variables The (Boolean) variables on which the operator is applied.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 146 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMaximum() [1/4]
void UniverseJavaCspSolver::addMaximum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
op The relational operator to use to compare the maximum.
value The variable to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1548 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMaximum() [2/4]
void UniverseJavaCspSolver::addMaximum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
op The relational operator to use to compare the maximum.
value The value to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1538 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMaximum() [3/4]
void UniverseJavaCspSolver::addMaximum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
op The operator checking whether the maximum is in the set.
set The allowed values for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1563 of file UniverseJavaCspSolver.cpp.
addMaximum() [4/4]
void UniverseJavaCspSolver::addMaximum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
op The operator checking whether the maximum is in the range.
min The minimum value for the maximum.
max The maximum value for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1558 of file UniverseJavaCspSolver.cpp.
addMaximumArg() [1/4]
void UniverseJavaCspSolver::addMaximumArg (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
variables The variables to compute the maximum of.
op The relational operator to use to compare the maximum.
value The variable to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1629 of file UniverseJavaCspSolver.cpp.
addMaximumArg() [2/4]
void UniverseJavaCspSolver::addMaximumArg (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
variables The variables to compute the maximum of.
op The relational operator to use to compare the maximum.
value The value to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1624 of file UniverseJavaCspSolver.cpp.
addMaximumArg() [3/4]
void UniverseJavaCspSolver::addMaximumArg (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
variables The variables to compute the maximum of.
op The operator checking whether the maximum is in the set.
set The allowed values for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1641 of file UniverseJavaCspSolver.cpp.
addMaximumArg() [4/4]
void UniverseJavaCspSolver::addMaximumArg (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
variables The variables to compute the maximum of.
op The operator checking whether the maximum is in the range.
min The minimum value for the maximum.
max The maximum value for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1635 of file UniverseJavaCspSolver.cpp.
addMaximumArgIntension() [1/4]
void UniverseJavaCspSolver::addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The relational operator to use to compare the maximum.
value The variable to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1652 of file UniverseJavaCspSolver.cpp.
addMaximumArgIntension() [2/4]
void UniverseJavaCspSolver::addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The relational operator to use to compare the maximum.
value The value to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1646 of file UniverseJavaCspSolver.cpp.
addMaximumArgIntension() [3/4]
void UniverseJavaCspSolver::addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The operator checking whether the maximum is in the set.
set The allowed values for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1664 of file UniverseJavaCspSolver.cpp.
addMaximumArgIntension() [4/4]
void UniverseJavaCspSolver::addMaximumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a maximum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The operator checking whether the maximum is in the range.
min The minimum value for the maximum.
max The maximum value for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1658 of file UniverseJavaCspSolver.cpp.
addMaximumIndex() [1/4]
void UniverseJavaCspSolver::addMaximumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
startIndex The index at which to start looking for the maximum
index The variable encoding the index at which the maximum is.
op The relational operator to use to compare the maximum.
value The variable to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1573 of file UniverseJavaCspSolver.cpp.
addMaximumIndex() [2/4]
void UniverseJavaCspSolver::addMaximumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
startIndex The index at which to start looking for the maximum
index The variable encoding the index at which the maximum is.
op The relational operator to use to compare the maximum.
value The value to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1568 of file UniverseJavaCspSolver.cpp.
addMaximumIndex() [3/4]
void UniverseJavaCspSolver::addMaximumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
startIndex The index at which to start looking for the maximum
index The variable encoding the index at which the maximum is.
op The operator checking whether the maximum is in the set.
set The allowed values for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1584 of file UniverseJavaCspSolver.cpp.
addMaximumIndex() [4/4]
void UniverseJavaCspSolver::addMaximumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a maximum constraint.
Parameters
variables The variables to compute the maximum of.
startIndex The index at which to start looking for the maximum
index The variable encoding the index at which the maximum is.
op The operator checking whether the maximum is in the range.
min The minimum value for the maximum.
max The maximum value for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1578 of file UniverseJavaCspSolver.cpp.
addMaximumIntension() [1/4]
void UniverseJavaCspSolver::addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a maximum constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The relational operator to use to compare the maximum.
value The variable to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1600 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMaximumIntension() [2/4]
void UniverseJavaCspSolver::addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a maximum constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The relational operator to use to compare the maximum.
value The value to compare the maximum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1590 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMaximumIntension() [3/4]
void UniverseJavaCspSolver::addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a maximum constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The operator checking whether the maximum is in the set.
set The allowed values for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1618 of file UniverseJavaCspSolver.cpp.
addMaximumIntension() [4/4]
void UniverseJavaCspSolver::addMaximumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a maximum constraint.
Parameters
intensionConstraints The intension constraints to compute the maximum of.
op The operator checking whether the maximum is in the range.
min The minimum value for the maximum.
max The maximum value for the maximum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1611 of file UniverseJavaCspSolver.cpp.
addMDD()
void UniverseJavaCspSolver::addMDD (const std::vector< std::string > & variables, const std::vector< UniverseTransition > & transitions) override virtual
Adds to this solver an mdd constraint.
Parameters
variables The variables encoding a path in the MDD.
transitions The transitions of the MDD.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2040 of file UniverseJavaCspSolver.cpp.
addMinimum() [1/4]
void UniverseJavaCspSolver::addMinimum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
op The relational operator to use to compare the minimum.
value The variable to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1416 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMinimum() [2/4]
void UniverseJavaCspSolver::addMinimum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
op The relational operator to use to compare the minimum.
value The value to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1406 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMinimum() [3/4]
void UniverseJavaCspSolver::addMinimum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
op The operator checking whether the minimum is in the set.
set The allowed values for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1431 of file UniverseJavaCspSolver.cpp.
addMinimum() [4/4]
void UniverseJavaCspSolver::addMinimum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
op The operator checking whether the minimum is in the range.
min The minimum value for the minimum.
max The maximum value for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1426 of file UniverseJavaCspSolver.cpp.
addMinimumArg() [1/4]
void UniverseJavaCspSolver::addMinimumArg (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
variables The variables to compute the minimum of.
op The relational operator to use to compare the minimum.
value The variable to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1497 of file UniverseJavaCspSolver.cpp.
addMinimumArg() [2/4]
void UniverseJavaCspSolver::addMinimumArg (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
variables The variables to compute the minimum of.
op The relational operator to use to compare the minimum.
value The value to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1492 of file UniverseJavaCspSolver.cpp.
addMinimumArg() [3/4]
void UniverseJavaCspSolver::addMinimumArg (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
variables The variables to compute the minimum of.
op The operator checking whether the minimum is in the set.
set The allowed values for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1509 of file UniverseJavaCspSolver.cpp.
addMinimumArg() [4/4]
void UniverseJavaCspSolver::addMinimumArg (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
variables The variables to compute the minimum of.
op The operator checking whether the minimum is in the range.
min The minimum value for the minimum.
max The maximum value for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1503 of file UniverseJavaCspSolver.cpp.
addMinimumArgIntension() [1/4]
void UniverseJavaCspSolver::addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The relational operator to use to compare the minimum.
value The variable to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1520 of file UniverseJavaCspSolver.cpp.
addMinimumArgIntension() [2/4]
void UniverseJavaCspSolver::addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The relational operator to use to compare the minimum.
value The value to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1514 of file UniverseJavaCspSolver.cpp.
addMinimumArgIntension() [3/4]
void UniverseJavaCspSolver::addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The operator checking whether the minimum is in the set.
set The allowed values for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1532 of file UniverseJavaCspSolver.cpp.
addMinimumArgIntension() [4/4]
void UniverseJavaCspSolver::addMinimumArgIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a minimum-arg constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The operator checking whether the minimum is in the range.
min The minimum value for the minimum.
max The maximum value for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1526 of file UniverseJavaCspSolver.cpp.
addMinimumIndex() [1/4]
void UniverseJavaCspSolver::addMinimumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
startIndex The index at which to start looking for the minimum
index The variable encoding the index at which the minimum is.
op The relational operator to use to compare the minimum.
value The variable to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1441 of file UniverseJavaCspSolver.cpp.
addMinimumIndex() [2/4]
void UniverseJavaCspSolver::addMinimumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
startIndex The index at which to start looking for the minimum
index The variable encoding the index at which the minimum is.
op The relational operator to use to compare the minimum.
value The value to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1436 of file UniverseJavaCspSolver.cpp.
addMinimumIndex() [3/4]
void UniverseJavaCspSolver::addMinimumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
startIndex The index at which to start looking for the minimum
index The variable encoding the index at which the minimum is.
op The operator checking whether the minimum is in the set.
set The allowed values for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1452 of file UniverseJavaCspSolver.cpp.
addMinimumIndex() [4/4]
void UniverseJavaCspSolver::addMinimumIndex (const std::vector< std::string > & variables, int startIndex, const std::string & index, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a minimum constraint.
Parameters
variables The variables to compute the minimum of.
startIndex The index at which to start looking for the minimum
index The variable encoding the index at which the minimum is.
op The operator checking whether the minimum is in the range.
min The minimum value for the minimum.
max The maximum value for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1446 of file UniverseJavaCspSolver.cpp.
addMinimumIntension() [1/4]
void UniverseJavaCspSolver::addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const std::string & value) override virtual
Adds to this solver a minimum constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The relational operator to use to compare the minimum.
value The variable to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1468 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMinimumIntension() [2/4]
void UniverseJavaCspSolver::addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a minimum constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The relational operator to use to compare the minimum.
value The value to compare the minimum with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1458 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addMinimumIntension() [3/4]
void UniverseJavaCspSolver::addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver a minimum constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The operator checking whether the minimum is in the set.
set The allowed values for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1486 of file UniverseJavaCspSolver.cpp.
addMinimumIntension() [4/4]
void UniverseJavaCspSolver::addMinimumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & intensionConstraints, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a minimum constraint.
Parameters
intensionConstraints The intension constraints to compute the minimum of.
op The operator checking whether the minimum is in the range.
min The minimum value for the minimum.
max The maximum value for the minimum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1479 of file UniverseJavaCspSolver.cpp.
addMultiDimensionalNoOverlap() [1/2]
void UniverseJavaCspSolver::addMultiDimensionalNoOverlap (const std::vector< std::vector< std::string >> & variables, const std::vector< std::vector< Universe::BigInteger >> & length) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The length associated to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1719 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addMultiDimensionalNoOverlap() [2/2]
void UniverseJavaCspSolver::addMultiDimensionalNoOverlap (const std::vector< std::vector< std::string >> & variables, const std::vector< std::vector< Universe::BigInteger >> & length, bool zeroIgnored) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The length associated to the variables.
zeroIgnored Whether 0-lengths should be ignored.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1728 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addMultiDimensionalNoOverlapVariableLength() [1/2]
void UniverseJavaCspSolver::addMultiDimensionalNoOverlapVariableLength (const std::vector< std::vector< std::string >> & variables, const std::vector< std::vector< std::string >> & length) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The variable for the length of the other variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1737 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addMultiDimensionalNoOverlapVariableLength() [2/2]
void UniverseJavaCspSolver::addMultiDimensionalNoOverlapVariableLength (const std::vector< std::vector< std::string >> & variables, const std::vector< std::vector< std::string >> & length, bool zeroIgnored) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The variable for the length of the other variables.
zeroIgnored Whether 0-lengths should be ignored.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1746 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addNoOverlap() [1/2]
void UniverseJavaCspSolver::addNoOverlap (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & length) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The length associated to the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1670 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addNoOverlap() [2/2]
void UniverseJavaCspSolver::addNoOverlap (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & length, bool zeroIgnored) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The length associated to the variables.
zeroIgnored Whether 0-lengths should be ignored.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1678 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addNoOverlapVariableLength() [1/2]
void UniverseJavaCspSolver::addNoOverlapVariableLength (const std::vector< std::string > & variables, const std::vector< std::string > & length) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The variable for the length of the other variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1687 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addNoOverlapVariableLength() [2/2]
void UniverseJavaCspSolver::addNoOverlapVariableLength (const std::vector< std::string > & variables, const std::vector< std::string > & length, bool zeroIgnored) override virtual
Adds to this solver a no-overlap constraint.
Parameters
variables The variables appearing in the constraint.
length The variable for the length of the other variables.
zeroIgnored Whether 0-lengths should be ignored.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1696 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addNotAllEqual()
void UniverseJavaCspSolver::addNotAllEqual (const std::vector< std::string > & variables) override virtual
Adds to this solver a not-all-equal constraint.
Parameters
variables The variables that should not be all equal.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1795 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addNValues() [1/4]
void UniverseJavaCspSolver::addNValues (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & nb) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
nb The variable counting the number of distinct values.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 504 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValues() [2/4]
void UniverseJavaCspSolver::addNValues (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & nb) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
nb The number of distinct values to count.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 483 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValues() [3/4]
void UniverseJavaCspSolver::addNValues (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The set operator used in the constraint.
set The allowed numbers of distinct values.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 538 of file UniverseJavaCspSolver.cpp.
addNValues() [4/4]
void UniverseJavaCspSolver::addNValues (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
set The set operator used in the constraint.
min The minimum number of distinct values to count.
max The maximum number of distinct values to count.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 525 of file UniverseJavaCspSolver.cpp.
addNValuesExcept() [1/4]
void UniverseJavaCspSolver::addNValuesExcept (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & nb, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
nb The variable counting the number of distinct values.
except The values that should not be counted.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 514 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValuesExcept() [2/4]
void UniverseJavaCspSolver::addNValuesExcept (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & nb, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
nb The number of distinct values to count.
except The values that should not be counted.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 493 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValuesExcept() [3/4]
void UniverseJavaCspSolver::addNValuesExcept (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
op The set operator used in the constraint.
set The allowed numbers of distinct values.
except The values that should not be counted.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 544 of file UniverseJavaCspSolver.cpp.
addNValuesExcept() [4/4]
void UniverseJavaCspSolver::addNValuesExcept (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max, const std::vector< Universe::BigInteger > & except) override virtual
Adds to this solver an n-values constraint.
Parameters
variables The variables appearing in the constraint.
set The set operator used in the constraint.
min The minimum number of distinct values to count.
max The maximum number of distinct values to count.
except The values that should not be counted.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 531 of file UniverseJavaCspSolver.cpp.
addNValuesIntension() [1/4]
void UniverseJavaCspSolver::addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseRelationalOperator op, const std::string & nb) override virtual
Adds to this solver an n-values constraint.
Parameters
expressions The expressions appearing in the constraint.
op The relational operator used in the constraint.
nb The variable counting the number of distinct values.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 561 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValuesIntension() [2/4]
void UniverseJavaCspSolver::addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseRelationalOperator op, const Universe::BigInteger & nb) override virtual
Adds to this solver an n-values constraint.
Parameters
expressions The expressions appearing in the constraint.
op The relational operator used in the constraint.
nb The number of distinct values to count.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 551 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addNValuesIntension() [3/4]
void UniverseJavaCspSolver::addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & set) override virtual
Adds to this solver an n-values constraint.
Parameters
expressions The expressions appearing in the constraint.
op The set operator used in the constraint.
set The allowed numbers of distinct values.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 577 of file UniverseJavaCspSolver.cpp.
addNValuesIntension() [4/4]
void UniverseJavaCspSolver::addNValuesIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver an n-values constraint.
Parameters
expressions The expressions appearing in the constraint.
op The set operator used in the constraint.
min The minimum number of distinct values to count.
max The maximum number of distinct values to count.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 571 of file UniverseJavaCspSolver.cpp.
addOrdered()
void UniverseJavaCspSolver::addOrdered (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver an ordered constraint.
Parameters
variables The variables that should be ordered.
op The relational operator defining the order of the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1755 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addOrderedWithConstantLength()
void UniverseJavaCspSolver::addOrderedWithConstantLength (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & lengths, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver an ordered constraint.
Parameters
variables The variables that should be ordered.
lengths The lengths that must exist between two consecutive variables.
op The relational operator defining the order of the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1763 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addOrderedWithVariableLength()
void UniverseJavaCspSolver::addOrderedWithVariableLength (const std::vector< std::string > & variables, const std::vector< std::string > & lengths, Universe::UniverseRelationalOperator op) override virtual
Adds to this solver an ordered constraint.
Parameters
variables The variables that should be ordered.
lengths The variables encoding the lengths that must exist between two consecutive variables.
op The relational operator defining the order of the variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1773 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrecedence() [1/2]
void UniverseJavaCspSolver::addPrecedence (const std::vector< std::string > & variables) override virtual
Adds to this solver a precedence constraint.
Parameters
variables The variables appearing in the constraint.
Implements Universe::IUniverseCspSolver.
Definition at line 1248 of file UniverseJavaCspSolver.cpp.
addPrecedence() [2/2]
void UniverseJavaCspSolver::addPrecedence (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, bool covered) override virtual
Adds to this solver a precedence constraint.
Parameters
variables The variables appearing in the constraint.
values The values on which the precedence constraint applies.
covered Whether each value of the specified list must be assigned by at least one variable in the scope of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1253 of file UniverseJavaCspSolver.cpp.
addPrimitive() [1/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseArithmeticOperator arithOp, const std::string & leftHandSide, Universe::UniverseRelationalOperator relOp, const std::string & rightHandSide) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
arithOp The arithmetic operator applied on the variable.
leftHandSide The variable on the left-hand side of the constraint.
relOp The relational operator used to compare the right-hand side with the left-hand side.
rightHandSide The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1363 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [2/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseArithmeticOperator arithOp, const std::string & leftHandSide, Universe::UniverseRelationalOperator relOp, const Universe::BigInteger & rightHandSide) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
arithOp The arithmetic operator applied on the variable.
leftHandSide The variable on the left-hand side of the constraint.
relOp The relational operator used to compare the right-hand side with the left-hand side.
rightHandSide The value on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1339 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [3/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseArithmeticOperator arithOp, const Universe::BigInteger & leftHandSide, Universe::UniverseRelationalOperator relOp, const std::string & rightHandSide) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
arithOp The arithmetic operator applied on the variable.
leftHandSide The value on the left-hand side of the constraint.
relOp The relational operator used to compare the right-hand side with the left-hand side.
rightHandSide The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1351 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [4/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseArithmeticOperator arithOp, const Universe::BigInteger & leftHandSide, Universe::UniverseRelationalOperator relOp, const Universe::BigInteger & rightHandSide) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
arithOp The arithmetic operator applied on the variable.
leftHandSide The value on the left-hand side of the constraint.
relOp The relational operator used to compare the right-hand side with the left-hand side.
rightHandSide The value on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1327 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [5/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
op The operator used in the constraint.
value The value to compare the variable with.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1317 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [6/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
op The operator defining whether the values are allowed or forbidden.
values The set of values on which the operator is applied.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1385 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [7/8]
void UniverseJavaCspSolver::addPrimitive (const std::string & variable, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a primitive constraint.
Parameters
variable The variable appearing in the constraint.
op The operator defining whether the values are allowed or forbidden.
min The minimum value of the range on which the operator is applied.
max The maximum value of the range on which the operator is applied.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1395 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addPrimitive() [8/8]
void UniverseJavaCspSolver::addPrimitive (Universe::UniverseArithmeticOperator arithOp, const std::string & variable, const std::string & rightHandSide) override virtual
Adds to this solver a primitive constraint.
Parameters
arithOp The arithmetic operator applied on the variable.
variable The variable on which the operator is applied.
rightHandSide The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1375 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addRegular()
void UniverseJavaCspSolver::addRegular (const std::vector< std::string > & variables, const std::vector< UniverseTransition > & transitions, const std::string & startState, const std::vector< std::string > & finalStates) override virtual
Adds to this solver a regular constraint.
Parameters
variables The variables encoding a path in the MDD.
transitions The transitions of the MDD.
startState The variable encoding the start state of the MDD.
finalStates The variables encoding the final states of the MDD.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2045 of file UniverseJavaCspSolver.cpp.
addStretch() [1/2]
void UniverseJavaCspSolver::addStretch (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::vector< Universe::BigInteger > & widthsMin, const std::vector< Universe::BigInteger > & widthsMax) override virtual
Adds to this solver a stretch constraint.
Parameters
variables The variables appearing in the constraint.
values The values to assign to the variables.
widthsMin The minimum widths of the sequences to build.
widthsMax The maximum widths of the sequences to build.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1115 of file UniverseJavaCspSolver.cpp.
addStretch() [2/2]
void UniverseJavaCspSolver::addStretch (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & values, const std::vector< Universe::BigInteger > & widthsMin, const std::vector< Universe::BigInteger > & widthsMax, const std::vector< std::vector< Universe::BigInteger >> & patterns) override virtual
Adds to this solver a stretch constraint.
Parameters
variables The variables appearing in the constraint.
values The values to assign to the variables.
widthsMin The minimum widths of the sequences to build.
widthsMax The maximum widths of the sequences to build.
patterns The possible successive values between stretches.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1121 of file UniverseJavaCspSolver.cpp.
addSum() [1/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1864 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSum() [2/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1833 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSum() [3/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1882 of file UniverseJavaCspSolver.cpp.
addSum() [4/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1876 of file UniverseJavaCspSolver.cpp.
addSum() [5/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1854 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSum() [6/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1823 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSum() [7/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1849 of file UniverseJavaCspSolver.cpp.
addSum() [8/8]
void UniverseJavaCspSolver::addSum (const std::vector< std::string > & variables, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1844 of file UniverseJavaCspSolver.cpp.
addSumIntension() [1/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1930 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntension() [2/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1897 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntension() [3/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1948 of file UniverseJavaCspSolver.cpp.
addSumIntension() [4/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1941 of file UniverseJavaCspSolver.cpp.
addSumIntension() [5/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1920 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntension() [6/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1887 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntension() [7/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1914 of file UniverseJavaCspSolver.cpp.
addSumIntension() [8/8]
void UniverseJavaCspSolver::addSumIntension (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1908 of file UniverseJavaCspSolver.cpp.
addSumIntensionWithVariableCoefficients() [1/4]
void UniverseJavaCspSolver::addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< std::string > & coefficients, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2003 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntensionWithVariableCoefficients() [2/4]
void UniverseJavaCspSolver::addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< std::string > & coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1991 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumIntensionWithVariableCoefficients() [3/4]
void UniverseJavaCspSolver::addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< std::string > & coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2021 of file UniverseJavaCspSolver.cpp.
addSumIntensionWithVariableCoefficients() [4/4]
void UniverseJavaCspSolver::addSumIntensionWithVariableCoefficients (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< std::string > & coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
expressions The expressions appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 2015 of file UniverseJavaCspSolver.cpp.
addSumWithVariableCoefficients() [1/4]
void UniverseJavaCspSolver::addSumWithVariableCoefficients (const std::vector< std::string > & variables, const std::vector< std::string > & coefficients, Universe::UniverseRelationalOperator op, const std::string & rightVariable) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
rightVariable The variable on the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1966 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumWithVariableCoefficients() [2/4]
void UniverseJavaCspSolver::addSumWithVariableCoefficients (const std::vector< std::string > & variables, const std::vector< std::string > & coefficients, Universe::UniverseRelationalOperator op, const Universe::BigInteger & value) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The relational operator used in the constraint.
value The value of the right-hand side of the constraint.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1955 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
addSumWithVariableCoefficients() [3/4]
void UniverseJavaCspSolver::addSumWithVariableCoefficients (const std::vector< std::string > & variables, const std::vector< std::string > & coefficients, Universe::UniverseSetBelongingOperator op, const std::vector< Universe::BigInteger > & values) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
values The set of allowed values for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1984 of file UniverseJavaCspSolver.cpp.
addSumWithVariableCoefficients() [4/4]
void UniverseJavaCspSolver::addSumWithVariableCoefficients (const std::vector< std::string > & variables, const std::vector< std::string > & coefficients, Universe::UniverseSetBelongingOperator op, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds to this solver a sum constraint.
Parameters
variables The variables appearing in the constraint.
coefficients The coefficients of the variables in the sum.
op The set operator used in the constraint.
min The minimum value for the sum.
max The maximum value for the sum.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1977 of file UniverseJavaCspSolver.cpp.
addSupport() [1/2]
void UniverseJavaCspSolver::addSupport (const std::string & variable, const std::vector< Universe::BigInteger > & allowedValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the support of a variable.
Parameters
variable The variable for which the support is given.
allowedValues The values allowed for the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1258 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
addSupport() [2/2]
void UniverseJavaCspSolver::addSupport (const std::vector< std::string > & variableTuple, const std::vector< std::vector< Universe::BigInteger >> & allowedValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the support of a tuple of variables.
Parameters
variableTuple The tuple of variables for which the support is given.
allowedValues The values allowed for the tuple variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1270 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
addSupportSymbolic() [1/2]
void UniverseJavaCspSolver::addSupportSymbolic (const std::string & variable, const std::vector< std::string > & allowedValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the support of a variable.
Parameters
variable The variable for which the support is given.
allowedValues The values allowed for the variable.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1266 of file UniverseJavaCspSolver.cpp.
addSupportSymbolic() [2/2]
void UniverseJavaCspSolver::addSupportSymbolic (const std::vector< std::string > & variableTuple, const std::vector< std::vector< std::string >> & allowedValues, bool hasStar) override virtual
Adds to this solver an extension constraint describing the support of a tuple of variables.
Parameters
variableTuple The tuple of variables for which the support is given.
allowedValues The values allowed for the tuple variables.
Exceptions
UniverseContradictionException If adding the constraint results in a trivial inconsistency.
Implements Universe::IUniverseCspSolver.
Definition at line 1279 of file UniverseJavaCspSolver.cpp.
asList() [1/4]
JavaList UniverseJavaCspSolver::asList (const std::vector< std::string > & strings) static protected
Creates a JavaList corresponding to the given vector of strings.
Parameters
strings The vector of strings to transform into a list.
Returns
The created list.
Definition at line 2552 of file UniverseJavaCspSolver.cpp.
References Universe::JavaList::from().
asList() [2/4]
JavaList UniverseJavaCspSolver::asList (const std::vector< std::vector< std::string >> & matrix) static protected
Creates a JavaList corresponding to the given vector of vector of strings.
Parameters
matrix The vector of vectors of strings to transform into a list.
Returns
The created list.
Definition at line 2559 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::JavaList::from().
asList() [3/4]
JavaList UniverseJavaCspSolver::asList (const std::vector< std::vector< Universe::BigInteger >> & matrix) static protected
Creates a JavaList corresponding to the given vector of big integers.
Parameters
matrix The vector of vectors of big integers to transform into a list.
Returns
The created list.
Definition at line 2545 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::JavaList::from().
Referenced by addAllDifferent(), addAllDifferentIntension(), addAllDifferentList(), addAllDifferentMatrix(), addAllEqual(), addAllEqualIntension(), addAmong(), addAtLeast(), addAtMost(), addCardinalityWithConstantValuesAndConstantCounts(), addCardinalityWithConstantValuesAndConstantIntervalCounts(), addCardinalityWithConstantValuesAndVariableCounts(), addCardinalityWithVariableValuesAndConstantCounts(), addCardinalityWithVariableValuesAndConstantIntervalCounts(), addCardinalityWithVariableValuesAndVariableCounts(), addChannel(), addClause(), addConflicts(), addExactly(), addInstantiation(), addMultiDimensionalNoOverlap(), addMultiDimensionalNoOverlapVariableLength(), addNoOverlap(), addNoOverlapVariableLength(), addNotAllEqual(), addSupport(), asList(), maximizeExpressionMaximum(), maximizeExpressionMinimum(), maximizeExpressionNValues(), maximizeExpressionProduct(), maximizeExpressionSum(), maximizeMaximum(), maximizeMinimum(), maximizeNValues(), maximizeProduct(), maximizeSum(), minimizeExpressionMaximum(), minimizeExpressionMinimum(), minimizeExpressionNValues(), minimizeExpressionProduct(), minimizeExpressionSum(), minimizeMaximum(), minimizeMinimum(), minimizeNValues(), minimizeProduct(), and minimizeSum().
asList() [4/4]
JavaList UniverseJavaCspSolver::asList (const std::vector< Universe::IUniverseIntensionConstraint * > & constraints) static protected
Creates a JavaList corresponding to the given vector of intension constraints.
Parameters
constraints The vector of intension constraints to transform into a list.
Returns
The created list.
Definition at line 2566 of file UniverseJavaCspSolver.cpp.
References Universe::JavaList::from().
maximizeExpression()
void UniverseJavaCspSolver::maximizeExpression (Universe::IUniverseIntensionConstraint * expression) override virtual
Adds to this solver an objective function to maximize the value of an expression.
Parameters
expression The expression to maximize the value of.
Implements Universe::IUniverseCspSolver.
Definition at line 2103 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
maximizeExpressionMaximum() [1/2]
void UniverseJavaCspSolver::maximizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to maximize the maximum of expressions.
Parameters
expressions The expressions to maximize the maximum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2311 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionMaximum() [2/2]
void UniverseJavaCspSolver::maximizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the maximum of expressions.
Parameters
expressions The expressions to maximize the maximum of.
coefficients The coefficients of the expressions in the maximum.
Implements Universe::IUniverseCspSolver.
Definition at line 2317 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionMinimum() [1/2]
void UniverseJavaCspSolver::maximizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to maximize the minimum of expressions.
Parameters
expressions The expressions to maximize the minimum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2257 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionMinimum() [2/2]
void UniverseJavaCspSolver::maximizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the minimum of expressions.
Parameters
expressions The expressions to maximize the minimum of.
coefficients The coefficients of the expressions in the minimum.
Implements Universe::IUniverseCspSolver.
Definition at line 2263 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionNValues() [1/2]
void UniverseJavaCspSolver::maximizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to maximize the number of values assigned to expressions.
Parameters
expressions The expressions to maximize the number of values of.
Implements Universe::IUniverseCspSolver.
Definition at line 2365 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionNValues() [2/2]
void UniverseJavaCspSolver::maximizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the number of values assigned to expressions.
Parameters
expressions The expressions to maximize the number of values of.
coefficients The coefficients of the expressions.
Implements Universe::IUniverseCspSolver.
Definition at line 2371 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionProduct() [1/2]
void UniverseJavaCspSolver::maximizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to maximize a product of expressions.
Parameters
expressions The expressions to maximize the product of.
Implements Universe::IUniverseCspSolver.
Definition at line 2203 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionProduct() [2/2]
void UniverseJavaCspSolver::maximizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize a product of expressions.
Parameters
expressions The expressions to maximize the product of.
coefficients The coefficients of the expressions in the product.
Implements Universe::IUniverseCspSolver.
Definition at line 2209 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionSum() [1/2]
void UniverseJavaCspSolver::maximizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to maximize a sum of expressions.
Parameters
expressions The expressions to maximize the sum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2149 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeExpressionSum() [2/2]
void UniverseJavaCspSolver::maximizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize a sum of expressions.
Parameters
expressions The expressions to maximize the sum of.
coefficients The coefficients of the expressions in the sum.
Implements Universe::IUniverseCspSolver.
Definition at line 2155 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeMaximum() [1/2]
void UniverseJavaCspSolver::maximizeMaximum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to maximize the maximum of variables.
Parameters
variables The variables to maximize the maximum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2298 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeMaximum() [2/2]
void UniverseJavaCspSolver::maximizeMaximum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the maximum of variables.
Parameters
variables The variables to maximize the maximum of.
coefficients The coefficients of the variables in the maximum.
Implements Universe::IUniverseCspSolver.
Definition at line 2304 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeMinimum() [1/2]
void UniverseJavaCspSolver::maximizeMinimum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to maximize the minimum of variables.
Parameters
variables The variables to maximize the minimum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2244 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeMinimum() [2/2]
void UniverseJavaCspSolver::maximizeMinimum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the minimum of variables.
Parameters
variables The variables to maximize the minimum of.
coefficients The coefficients of the variables in the minimum.
Implements Universe::IUniverseCspSolver.
Definition at line 2250 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeNValues() [1/2]
void UniverseJavaCspSolver::maximizeNValues (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to maximize the number of values assigned to variables.
Parameters
variables The variables to maximize the number of values of.
Implements Universe::IUniverseCspSolver.
Definition at line 2352 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeNValues() [2/2]
void UniverseJavaCspSolver::maximizeNValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize the number of values assigned to variables.
Parameters
variables The variables to maximize the number of values of.
coefficients The coefficients of the variables.
Implements Universe::IUniverseCspSolver.
Definition at line 2358 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeProduct() [1/2]
void UniverseJavaCspSolver::maximizeProduct (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to maximize a product of variables.
Parameters
variables The variables to maximize the product of.
Implements Universe::IUniverseCspSolver.
Definition at line 2190 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeProduct() [2/2]
void UniverseJavaCspSolver::maximizeProduct (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize a product of variables.
Parameters
variables The variables to maximize the product of.
coefficients The coefficients of the variables in the product.
Implements Universe::IUniverseCspSolver.
Definition at line 2196 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeSum() [1/2]
void UniverseJavaCspSolver::maximizeSum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to maximize a sum of variables.
Parameters
variables The variables to maximize the sum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2136 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
maximizeSum() [2/2]
void UniverseJavaCspSolver::maximizeSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to maximize a sum of variables.
Parameters
variables The variables to maximize the sum of.
coefficients The coefficients of the variables in the sum.
Implements Universe::IUniverseCspSolver.
Definition at line 2142 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
maximizeVariable()
void UniverseJavaCspSolver::maximizeVariable (const std::string & variable) override virtual
Adds to this solver an objective function to maximize the value assigned to a variable.
Parameters
variable The variable to maximize the value of.
Implements Universe::IUniverseCspSolver.
Definition at line 2091 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
minimizeExpression()
void UniverseJavaCspSolver::minimizeExpression (Universe::IUniverseIntensionConstraint * expression) override virtual
Adds to this solver an objective function to minimize the value of an expression.
Parameters
expression The expression to minimize the value of.
Implements Universe::IUniverseCspSolver.
Definition at line 2097 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
minimizeExpressionMaximum() [1/2]
void UniverseJavaCspSolver::minimizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to minimize the maximum of expressions.
Parameters
expressions The expressions to minimize the maximum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2284 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionMaximum() [2/2]
void UniverseJavaCspSolver::minimizeExpressionMaximum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the maximum of expressions.
Parameters
expressions The expressions to minimize the maximum of.
coefficients The coefficients of the expressions in the maximum.
Implements Universe::IUniverseCspSolver.
Definition at line 2290 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionMinimum() [1/2]
void UniverseJavaCspSolver::minimizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to minimize the minimum of expressions.
Parameters
expressions The expressions to minimize the minimum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2230 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionMinimum() [2/2]
void UniverseJavaCspSolver::minimizeExpressionMinimum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the minimum of expressions.
Parameters
expressions The expressions to minimize the minimum of.
coefficients The coefficients of the expressions in the minimum.
Implements Universe::IUniverseCspSolver.
Definition at line 2236 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionNValues() [1/2]
void UniverseJavaCspSolver::minimizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to minimize the number of values assigned to expressions.
Parameters
expressions The expressions to minimize the number of values of.
Implements Universe::IUniverseCspSolver.
Definition at line 2338 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionNValues() [2/2]
void UniverseJavaCspSolver::minimizeExpressionNValues (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the number of values assigned to expressions.
Parameters
expressions The expressions to minimize the number of values of.
coefficients The coefficients of the expressions.
Implements Universe::IUniverseCspSolver.
Definition at line 2344 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionProduct() [1/2]
void UniverseJavaCspSolver::minimizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to minimize a product of expressions.
Parameters
expressions The expressions to minimize the product of.
Implements Universe::IUniverseCspSolver.
Definition at line 2176 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionProduct() [2/2]
void UniverseJavaCspSolver::minimizeExpressionProduct (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize a product of expressions.
Parameters
expressions The expressions to minimize the product of.
coefficients The coefficients of the expressions in the product.
Implements Universe::IUniverseCspSolver.
Definition at line 2182 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionSum() [1/2]
void UniverseJavaCspSolver::minimizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions) override virtual
Adds to this solver an objective function to minimize a sum of expressions.
Parameters
expressions The expressions to minimize the sum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2122 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeExpressionSum() [2/2]
void UniverseJavaCspSolver::minimizeExpressionSum (const std::vector< Universe::IUniverseIntensionConstraint * > & expressions, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize a sum of expressions.
Parameters
expressions The expressions to minimize the sum of.
coefficients The coefficients of the expressions in the sum.
Implements Universe::IUniverseCspSolver.
Definition at line 2128 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeMaximum() [1/2]
void UniverseJavaCspSolver::minimizeMaximum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to minimize the maximum of variables.
Parameters
variables The variables to minimize the maximum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2271 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeMaximum() [2/2]
void UniverseJavaCspSolver::minimizeMaximum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the maximum of variables.
Parameters
variables The variables to minimize the maximum of.
coefficients The coefficients of the variables in the maximum.
Implements Universe::IUniverseCspSolver.
Definition at line 2277 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeMinimum() [1/2]
void UniverseJavaCspSolver::minimizeMinimum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to minimize the minimum of variables.
Parameters
variables The variables to minimize the minimum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2217 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeMinimum() [2/2]
void UniverseJavaCspSolver::minimizeMinimum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the minimum of variables.
Parameters
variables The variables to minimize the minimum of.
coefficients The coefficients of the variables in the minimum.
Implements Universe::IUniverseCspSolver.
Definition at line 2223 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeNValues() [1/2]
void UniverseJavaCspSolver::minimizeNValues (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to minimize the number of values assigned to variables.
Parameters
variables The variables to minimize the number of values of.
Implements Universe::IUniverseCspSolver.
Definition at line 2325 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeNValues() [2/2]
void UniverseJavaCspSolver::minimizeNValues (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize the number of values assigned to variables.
Parameters
variables The variables to minimize the number of values of.
coefficients The coefficients of the variables.
Implements Universe::IUniverseCspSolver.
Definition at line 2331 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeProduct() [1/2]
void UniverseJavaCspSolver::minimizeProduct (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to minimize a product of variables.
Parameters
variables The variables to minimize the product of.
Implements Universe::IUniverseCspSolver.
Definition at line 2163 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeProduct() [2/2]
void UniverseJavaCspSolver::minimizeProduct (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize a product of variables.
Parameters
variables The variables to minimize the product of.
coefficients The coefficients of the variables in the product.
Implements Universe::IUniverseCspSolver.
Definition at line 2169 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeSum() [1/2]
void UniverseJavaCspSolver::minimizeSum (const std::vector< std::string > & variables) override virtual
Adds to this solver an objective function to minimize a sum of variables.
Parameters
variables The variables to minimize the sum of.
Implements Universe::IUniverseCspSolver.
Definition at line 2109 of file UniverseJavaCspSolver.cpp.
References asList(), and Universe::UniverseJavaSolver::interface.
minimizeSum() [2/2]
void UniverseJavaCspSolver::minimizeSum (const std::vector< std::string > & variables, const std::vector< Universe::BigInteger > & coefficients) override virtual
Adds to this solver an objective function to minimize a sum of variables.
Parameters
variables The variables to minimize the sum of.
coefficients The coefficients of the variables in the sum.
Implements Universe::IUniverseCspSolver.
Definition at line 2115 of file UniverseJavaCspSolver.cpp.
References asList(), Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
minimizeVariable()
void UniverseJavaCspSolver::minimizeVariable (const std::string & variable) override virtual
Adds to this solver an objective function to minimize the value assigned to a variable.
Parameters
variable The variable to minimize the value of.
Implements Universe::IUniverseCspSolver.
Definition at line 2085 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
newVariable() [1/4]
void UniverseJavaCspSolver::newVariable (const std::string & id, const std::vector< int > & values) override virtual
Adds a new variable to this solver.
Parameters
id The identifier of the variable to create.
values The values of the domain of the variable.
Implements Universe::IUniverseCspSolver.
Definition at line 78 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSatSolver::asList(), and Universe::UniverseJavaSolver::interface.
newVariable() [2/4]
void UniverseJavaCspSolver::newVariable (const std::string & id, const std::vector< Universe::BigInteger > & values) override virtual
Adds a new variable to this solver.
Parameters
id The identifier of the variable to create.
values The values of the domain of the variable.
Implements Universe::IUniverseCspSolver.
Definition at line 86 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::asList(), and Universe::UniverseJavaSolver::interface.
newVariable() [3/4]
void UniverseJavaCspSolver::newVariable (const std::string & id, const Universe::BigInteger & min, const Universe::BigInteger & max) override virtual
Adds a new variable to this solver.
Parameters
id The identifier of the variable to create.
min The minimum value of the domain of the variable.
max The maximum value of the domain of the variable.
Implements Universe::IUniverseCspSolver.
Definition at line 69 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface, and Universe::JavaBigInteger::newInstance().
newVariable() [4/4]
void UniverseJavaCspSolver::newVariable (const std::string & id, int min, int max) override virtual
Adds a new variable to this solver.
Parameters
id The identifier of the variable to create.
min The minimum value of the domain of the variable.
max The maximum value of the domain of the variable.
Implements Universe::IUniverseCspSolver.
Definition at line 62 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::interface.
newVariableSymbolic()
void UniverseJavaCspSolver::newVariableSymbolic (const std::string & id, const std::vector< std::string > & values) override virtual
Adds a new symbolic variable to this solver.
Parameters
id The identifier of the variable to create.
values The values of the domain of the variable.
Implements Universe::IUniverseCspSolver.
Definition at line 94 of file UniverseJavaCspSolver.cpp.
solve()
UniverseSolverResult UniverseJavaCspSolver::solve (const std::vector< UniverseAssumption< BigInteger >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::UniverseJavaSolver.
Definition at line 2387 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaSolver::solve().
solveBoolean()
UniverseSolverResult UniverseJavaCspSolver::solveBoolean (const std::vector< UniverseAssumption< bool >> & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving.
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::IUniverseSatSolver.
Definition at line 2383 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::solveBoolean().
solveDimacs()
UniverseSolverResult UniverseJavaCspSolver::solveDimacs (const std::vector< int > & assumptions) override virtual
Solves the problem associated to this solver.
Parameters
assumptions The assumptions to consider when solving (as a set of literals).
Returns
The outcome of the search conducted by the solver.
Reimplemented from Universe::IUniverseSatSolver.
Definition at line 2379 of file UniverseJavaCspSolver.cpp.
References Universe::UniverseJavaPseudoBooleanSolver::solveDimacs().
toJavaArithmeticOperator()
JavaObject UniverseJavaCspSolver::toJavaArithmeticOperator (Universe::UniverseArithmeticOperator op) static protected
Gives the Java object representing an arithmetic operator.
Parameters
op The arithmetic operator to get the Java representation of.
Returns
The JavaObject representing the operator.
Definition at line 2427 of file UniverseJavaCspSolver.cpp.
toJavaBooleanOperator()
JavaObject UniverseJavaCspSolver::toJavaBooleanOperator (Universe::UniverseBooleanOperator op) static protected
Gives the Java object representing a Boolean operator.
Parameters
op The Boolean operator to get the Java representation of.
Returns
The JavaObject representing the operator.
Definition at line 2391 of file UniverseJavaCspSolver.cpp.
toJavaRelationalOperator()
JavaObject UniverseJavaCspSolver::toJavaRelationalOperator (Universe::UniverseRelationalOperator op) static protected
Gives the Java object representing a relational operator.
Parameters
op The relational operator to get the Java representation of.
Returns
The JavaObject representing the operator.
Definition at line 2493 of file UniverseJavaCspSolver.cpp.
toJavaSetBelongingOperator()
JavaObject UniverseJavaCspSolver::toJavaSetBelongingOperator (Universe::UniverseSetBelongingOperator op) static protected
Gives the Java object representing a set-belonging operator.
Parameters
op The set-belonging operator to get the Java representation of.
Returns
The JavaObject representing the operator.
Definition at line 2529 of file UniverseJavaCspSolver.cpp.
The documentation for this class was generated from the following files:
UniverseJavaCspSolver.hpp
UniverseJavaCspSolver.cpp