UNIvERSE: Universe::UniverseJavaConstraint Class Reference
Universe::UniverseJavaConstraint Class Reference
#include <UniverseJavaConstraint.hpp>
Public Member Functions
~UniverseJavaConstraint () override=default
const double getScore () const override
easyjni::JavaObject operator* ()
const std::vector< Universe::IUniverseVariable * > & scope () override
Public Member Functions inherited from Universe::IUniverseConstraint
virtual ~IUniverseConstraint ()=default
Static Public Member Functions
static Universe::IUniverseConstraint * of (easyjni::JavaObject constraint)
Detailed Description
The UniverseJavaConstraint class defines an adapter for an IUniverseConstraint written in Java (and implementing the interface provided by JUniverse).
Definition at line 44 of file UniverseJavaConstraint.hpp.
Constructor & Destructor Documentation
~UniverseJavaConstraint()
Universe::UniverseJavaConstraint::~UniverseJavaConstraint () override default
Destroys this UniverseJavaConstraint.
Member Function Documentation
getScore()
const double UniverseJavaConstraint::getScore () const override virtual
Gives the score of this constraint, as computed by the solver.
Returns
The score of the constraint.
Implements Universe::IUniverseConstraint.
Definition at line 83 of file UniverseJavaConstraint.cpp.
of()
IUniverseConstraint * UniverseJavaConstraint::of (easyjni::JavaObject constraint) static
Creates a new UniverseJavaConstraint from an existing Java object that is an instance of IUniverseConstraint.
Parameters
constraint The existing Java object.
Returns
The wrapper for the object.
Definition at line 57 of file UniverseJavaConstraint.cpp.
Referenced by Universe::UniverseJavaProblem::getConstraints(), Universe::UniverseJavaVariable::getConstraints(), and Universe::UniverseJavaSolver::getConstraints().
operator*()
JavaObject UniverseJavaConstraint::operator* ()
Gives the Java object that is wrapped in this UniverseJavaConstraint.
Returns
The wrapped Java object.
Definition at line 62 of file UniverseJavaConstraint.cpp.
scope()
const vector< IUniverseVariable * > & UniverseJavaConstraint::scope () override virtual
Gives the scope of this constraint, i.e., the variables that appear in this constraint.
Returns
The variables involved in this constraint.
Implements Universe::IUniverseConstraint.
Definition at line 66 of file UniverseJavaConstraint.cpp.
References Universe::JavaIterator::forIterable(), Universe::JavaIterator::hasNext(), and Universe::UniverseJavaVariable::of().
The documentation for this class was generated from the following files:
UniverseJavaConstraint.hpp
UniverseJavaConstraint.cpp