UNIvERSE: UniverseType.hpp File Reference
UniverseType.hpp File Reference
Defines various aliases for types used throughout Universe.
#include <string>
Typedefs
typedef long long Universe::BigInteger
typedef int Universe::UniverseOperator
Functions
Universe::BigInteger Universe::bigIntegerValueOf (const std::string &s)
std::string Universe::toString (const Universe::BigInteger &i)
Detailed Description
Defines various aliases for types used throughout Universe.
Author
Thibault Falque
Romain Wallon
Date
14/09/22
Copyright
Copyright (c) 2022 - Univ Artois & CNRS & Exakis Nelite.
License:\n This project is released under the GNU LGPL3 License.
Definition in file UniverseType.hpp.
Typedef Documentation
BigInteger
typedef long long Universe::BigInteger
BigInteger is an alias for long long when no big integer implementation is provided.
Definition at line 51 of file UniverseType.hpp.
UniverseOperator
typedef int Universe::UniverseOperator
An alias allowing to use any kind of operators in a method.
Definition at line 75 of file UniverseType.hpp.
Function Documentation
bigIntegerValueOf()
BigInteger Universe::bigIntegerValueOf (const std::string & s)
Converts a string into a big integer, depending on how BigIntegers are implemented.
Parameters
s The string to convert into a big integer.
Returns
The BigInteger encoded in s.
Definition at line 44 of file UniverseType.cpp.
References Universe::bigIntegerValueOf().
Referenced by Universe::JavaBigInteger::asBigInteger(), and Universe::bigIntegerValueOf().
toString()
string Universe::toString (const Universe::BigInteger & i)
Converts a big integer into a string, depending on how BigIntegers are implemented.
Parameters
i The big integer to convert into a string.
Returns
The string representation of i.
Definition at line 36 of file UniverseType.cpp.
References Universe::toString().
Referenced by Universe::JavaBigInteger::newInstance(), and Universe::toString().