UNIvERSE: Universe::IUniverseIntensionConstraintVisitor Class Reference
Universe::IUniverseIntensionConstraintVisitor Class Reference abstract
#include <IUniverseIntensionConstraintVisitor.hpp>
Public Member Functions
virtual ~IUniverseIntensionConstraintVisitor ()=default
virtual void visit (Universe::UniverseBinaryIntensionConstraint *constraint)=0
virtual void visit (Universe::UniverseConstantIntensionConstraint *constant)=0
virtual void visit (Universe::UniverseIfThenElseIntensionConstraint *ifThenElse)=0
virtual void visit (Universe::UniverseNaryIntensionConstraint *constraint)=0
virtual void visit (Universe::UniverseUnaryIntensionConstraint *constraint)=0
virtual void visit (Universe::UniverseVariableIntensionConstraint *variable)=0
Detailed Description
The IUniverseIntensionConstraintVisitor defines an interface for visiting intension constraints.
Definition at line 76 of file IUniverseIntensionConstraintVisitor.hpp.
Constructor & Destructor Documentation
~IUniverseIntensionConstraintVisitor()
virtual Universe::IUniverseIntensionConstraintVisitor::~IUniverseIntensionConstraintVisitor () virtual default
Destroys this IUniverseIntensionConstraintVisitor.
Member Function Documentation
visit() [1/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseBinaryIntensionConstraint * constraint) pure virtual
Visits a binary constraint that appears in an intension constraint.
Parameters
constraint The constraint to visit.
visit() [2/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseConstantIntensionConstraint * constant) pure virtual
Visits a constant that appears in an intension constraint.
Parameters
constant The constant to visit.
Referenced by Universe::UniverseBinaryIntensionConstraint::accept(), Universe::UniverseConstantIntensionConstraint::accept(), Universe::UniverseIfThenElseIntensionConstraint::accept(), Universe::UniverseNaryIntensionConstraint::accept(), Universe::UniverseUnaryIntensionConstraint::accept(), and Universe::UniverseVariableIntensionConstraint::accept().
visit() [3/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseIfThenElseIntensionConstraint * ifThenElse) pure virtual
Visits an if-then-else constraint that appears in an intension constraint.
Parameters
ifThenElse The constraint to visit.
visit() [4/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseNaryIntensionConstraint * constraint) pure virtual
Visits an n-ary constraint that appears in an intension constraint.
Parameters
constraint The constraint to visit.
visit() [5/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseUnaryIntensionConstraint * constraint) pure virtual
Visits a unary constraint that appears in an intension constraint.
Parameters
constraint The constraint to visit.
visit() [6/6]
virtual void Universe::IUniverseIntensionConstraintVisitor::visit (Universe::UniverseVariableIntensionConstraint * variable) pure virtual
Visits a variable that appears in an intension constraint.
Parameters
variable The variable to visit.
The documentation for this class was generated from the following file:
IUniverseIntensionConstraintVisitor.hpp