name: Continuous Integration

on:
  push:
    branches: [ "main", 'releases/**' ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  # build:
  #   strategy:
  #       matrix:
  #         os: [windows-latest, ubuntu-latest, macos-latest]
  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Configure CMake
  #       run: cmake -B ${{github.workspace}}/build-${{ matrix.os }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  #     - name: Build
  #       run: cmake --build ${{github.workspace}}/build-${{ matrix.os }} --config ${{env.BUILD_TYPE}}
  #     - name: Upload a Build Artifact
  #       uses: actions/upload-artifact@v3.1.1
  #       with:
  #         name: libcrillab-except-${{ matrix.os }}
  #         path: |
  #           ${{github.workspace}}/build-${{ matrix.os }}/*/crillab-except.*
  #           ${{github.workspace}}/build-${{ matrix.os }}/libcrillab-except.*
  #           ${{github.workspace}}/include/**.hpp
  docs:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
      && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with: { python-version: "3.8" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y

    - name: Build docs
      run: cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build"
        -P cmake/docs-ci.cmake

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
        publish_branch: doxygen