name: CMake Windows
on:
  push:
    branches: [ 'main', 'releases/**','test-github' ]
  pull_request:
    branches: [ 'main','test-github' ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        jdk: [17]
        gmp: ["On","Off"]
    name: ${{ matrix.os }}-gmp_${{ matrix.gmp }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Install Dependencies on Windows
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gmp mingw-w64-x86_64-toolchain git make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: msys2 -c "cmake -B D:/a/universe/universe/build-${{ matrix.os }}-gmp_${{ matrix.gmp }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCOMPILE_GMP=${{ matrix.gmp }}"
      - name: Build
        # Build your program with the given configuration
        run: msys2 -c "cmake --build D:/a/universe/universe/build-${{ matrix.os }}-gmp_${{ matrix.gmp }} --config ${{env.BUILD_TYPE}}"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: universe-${{ matrix.os }}-gmp_${{ matrix.gmp }}
          path: |
            D:/a/universe/universe/build-${{ matrix.os }}-gmp_${{ matrix.gmp }}/lib*.*
            D:/a/universe/universe/universe/include/*/*.hpp
            D:/a/universe/universe/universe/include/*/*/*.hpp
      - name: Create Release
        if: startsWith( github.ref, 'release' )
        uses: fnkr/github-action-ghr@v1.3

