name: CMake Unix System
on:
  push:
    branches: [ 'main', 'releases/**','test-github' ]
  pull_request:
    branches: [ 'main','test-github' ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-20.04]
          jdk: [17]
          gmp: ["On","Off"]
    name: ${{ matrix.os }}-gmp_${{ matrix.gmp }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Install Dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install build-essential libxml2 libxml2-dev libgmp-dev libtbb-dev
      - name: Install Dependencies on MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install gmp
          brew install libxml2 tbb
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build-${{ matrix.os }}-gmp_${{ matrix.gmp }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCOMPILE_GMP=${{ matrix.gmp }} -DGMP_INCLUDE_DIR=/usr/local/opt/gmp/include -DGMP_LIBRARY_DIR=/usr/local/opt/gmp/lib/libgmpxx.dylib
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build-${{ matrix.os }}-gmp_${{ matrix.gmp }} --config ${{env.BUILD_TYPE}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: universe-${{ matrix.os }}-gmp_${{ matrix.gmp }}
          path: |
            ${{github.workspace}}/build-${{ matrix.os }}-gmp_${{ matrix.gmp }}/lib*.*
            ${{github.workspace}}/universe/include/*/*.hpp
            ${{github.workspace}}/universe/include/*/*/*.hpp
      - name: Create Release
        if: startsWith( github.ref, 'release' )
        uses: fnkr/github-action-ghr@v1.3
      
