name: Deploy Doxygen

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
            packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen
      - name: Build
        run: |
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}      
            cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/build/website