name: Deploy Doxygen

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
            packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen
      - name: Build
        run:
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
          - cmake --build . --target doc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: doxygen
          folder: ./build/doc